import { Body, GeoVector, Ecliptic, MoonPhase } from "npm:astronomy-engine@2.1.19";

const PROVIDER="Astronomy Engine", PROVIDER_VERSION="2.1.19", CALCULATION_VERSION="atlas_sky_ephemeris_v1";
const SIGNS=["aries","taurus","gemini","cancer","leo","virgo","libra","scorpio","sagittarius","capricorn","aquarius","pisces"];
const MODES=["moveable","fixed","common","moveable","fixed","common","moveable","fixed","common","moveable","fixed","common"];
const norm=(n:number)=>((n%360)+360)%360;
function point(at:Date){const moonLon=norm(Ecliptic(GeoVector(Body.Moon,at,false)).elon),phase=norm(MoonPhase(at)),i=Math.floor(moonLon/30)%12;return{at,moonLon,sunLon:norm(moonLon-phase),phase,illumination:(1-Math.cos(phase*Math.PI/180))/2,sign:SIGNS[i],mode:MODES[i],phaseState:phase<180?"waxing":"waning"};}
function parts(d:Date,tz:string){const ps=new Intl.DateTimeFormat("en-US",{timeZone:tz,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23"}).formatToParts(d),o:Record<string,number>={};for(const p of ps)if(p.type!=="literal")o[p.type]=Number(p.value);return o;}
function localUtc(ds:string,h:number,m:number,tz:string){const [y,mo,d]=ds.split("-").map(Number),target=Date.UTC(y,mo-1,d,h,m,0);let g=new Date(target);for(let i=0;i<3;i++){const p=parts(g,tz),represented=Date.UTC(p.year,p.month-1,p.day,p.hour,p.minute,p.second);g=new Date(g.getTime()+target-represented);}return g;}
function addDays(ds:string,n:number){const [y,m,d]=ds.split("-").map(Number);return new Date(Date.UTC(y,m-1,d+n)).toISOString().slice(0,10);}
function refine(a:Date,b:Date,kind:string,oldValue:string){let lo=a.getTime(),hi=b.getTime();for(let i=0;i<20;i++){const mid=new Date((lo+hi)/2),p=point(mid),v=kind==="sign"?p.sign:p.phaseState;if(v===oldValue)lo=mid.getTime();else hi=mid.getTime();}return new Date(hi);}
function build(points:any[],kind:string){const out:any[]=[],val=(p:any)=>kind==="sign"?p.sign:p.phaseState;let current=val(points[0]),start=points[0].at;for(let i=1;i<points.length;i++){const next=val(points[i]);if(next!==current){const end=refine(points[i-1].at,points[i].at,kind,current),idx=kind==="sign"?SIGNS.indexOf(current):-1;out.push({window_kind:kind==="sign"?"moon_sign":"moon_phase_half",value_key:current,starts_at:start.toISOString(),ends_at:end.toISOString(),value_payload:kind==="sign"?{sign_index:idx,mode:MODES[idx]}:{phase_state:current}});current=next;start=end;}}const idx=kind==="sign"?SIGNS.indexOf(current):-1;out.push({window_kind:kind==="sign"?"moon_sign":"moon_phase_half",value_key:current,starts_at:start.toISOString(),ends_at:points[points.length-1].at.toISOString(),value_payload:kind==="sign"?{sign_index:idx,mode:MODES[idx]}:{phase_state:current}});return out;}
Deno.serve(async(req)=>{if(req.method!=="POST")return new Response(JSON.stringify({error:"POST required"}),{status:405,headers:{"content-type":"application/json"}});let b:any;try{b=await req.json();}catch{return new Response(JSON.stringify({error:"Invalid JSON"}),{status:400,headers:{"content-type":"application/json"}})}const tz=String(b.timezone||"America/Chicago"),start=String(b.start_date||new Date().toISOString().slice(0,10)),days=Math.max(1,Math.min(Number(b.days??90),120));if(!/^\d{4}-\d{2}-\d{2}$/.test(start))return new Response(JSON.stringify({error:"start_date must be YYYY-MM-DD"}),{status:400,headers:{"content-type":"application/json"}});const end=addDays(start,days),rangeStart=localUtc(start,0,0,tz),rangeEnd=localUtc(end,0,0,tz),scanStart=new Date(rangeStart.getTime()-17*86400000),scanEnd=new Date(rangeEnd.getTime()+17*86400000),hourly:any[]=[];for(let ms=scanStart.getTime();ms<=scanEnd.getTime();ms+=3600000)hourly.push(point(new Date(ms)));const sign=build(hourly,"sign"),phase=build(hourly,"phase"),overlap=(w:any)=>new Date(w.starts_at)<rangeEnd&&new Date(w.ends_at)>rangeStart;const windows=[...sign.filter(overlap),...phase.filter(overlap),...sign.filter(overlap).map((w:any)=>({window_kind:"moon_mode",value_key:w.value_payload.mode,starts_at:w.starts_at,ends_at:w.ends_at,value_payload:{moon_sign:w.value_key,sign_index:w.value_payload.sign_index}}))].map((w:any)=>({...w,timezone_name:tz,frame:"geocentric",zodiac_basis:w.window_kind==="moon_phase_half"?null:"tropical_true_ecliptic_of_date",source_provider:PROVIDER,source_version:PROVIDER_VERSION,metadata:{boundary_refinement:"hourly_scan_plus_binary_refinement",interpretation_prohibited:true}}));const samples:any[]=[];for(let i=0;i<days;i++){const serviceDate=addDays(start,i),at=localUtc(serviceDate,12,0,tz),p=point(at);samples.push({service_date:serviceDate,sampled_at:at.toISOString(),timezone_name:tz,frame:"geocentric",zodiac_basis:"tropical_true_ecliptic_of_date",moon_longitude_deg:p.moonLon,sun_longitude_deg:p.sunLon,moon_sign:p.sign,moon_sign_mode:p.mode,phase_angle_deg:p.phase,illumination_fraction:p.illumination,phase_state:p.phaseState,source_provider:PROVIDER,source_version:PROVIDER_VERSION,metadata:{sample_basis:"local_noon",interpretation_prohibited:true}});}return new Response(JSON.stringify({contractVersion:"atlas_sky_window_calculator_v1",range:{startDate:start,endDate:end,days,timeZone:tz,rangeStart:rangeStart.toISOString(),rangeEnd:rangeEnd.toISOString()},source:{provider:PROVIDER,version:PROVIDER_VERSION,calculationVersion:CALCULATION_VERSION},basis:{frame:"geocentric",zodiac:"tropical_true_ecliptic_of_date",dailySample:"local_noon"},samples,windows,interpretationProhibited:true}),{headers:{"content-type":"application/json"}});});
