import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./home.css";
import "./zones.css";
import "./task-feed.css";
import "./closeout-clean.css";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

const criticalAtlasCss = `
:root{--atlas-text:#303345;--atlas-muted:#6f7369;--atlas-border:#d8cdbd;--atlas-border-soft:#e5dbcc;--atlas-cream:#f6f2e8;--atlas-paper:#fffdf8;--atlas-purple:#a7abd6;}
*{box-sizing:border-box} body{margin:0;background:#e8e8f0;color:var(--atlas-text);font-family:var(--font-geist-sans),ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;} button,a,input,select,textarea{font:inherit} button{cursor:pointer} a{color:inherit;text-decoration:none}
.atlas-phone-shell{min-height:100dvh;display:flex;justify-content:center;align-items:flex-start;padding:10px;background:linear-gradient(135deg,#eeeff7,#d9dbe8)}
.atlas-phone{width:min(100%,820px);min-height:92dvh;background:var(--atlas-paper);border:2px solid var(--atlas-border);border-radius:34px;overflow:hidden;box-shadow:0 18px 45px rgba(43,35,22,.10)}
.atlas-phone-top,.atlas-dashboard-top{height:118px;padding:24px 28px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--atlas-border);background:rgba(255,253,248,.92)}
.atlas-phone-brand{display:grid;gap:2px}.atlas-phone-kicker{color:#858bb8;text-transform:uppercase;letter-spacing:.24em;font-size:13px;font-weight:900}.atlas-phone-title{font-size:34px;line-height:1;font-weight:950;letter-spacing:-.06em}.atlas-soft-badge{border:2px solid var(--atlas-border);background:var(--atlas-paper);border-radius:0;padding:5px 8px;color:var(--atlas-text);font-size:28px;line-height:1;font-weight:500}
.atlas-home-grid{display:grid;grid-template-columns:1fr 1fr;gap:20px;padding:20px}.atlas-home-box{min-height:280px;border:2px solid var(--atlas-border);border-radius:34px;padding:24px;text-align:left;overflow:hidden;display:flex;flex-direction:column;background:var(--atlas-paper);color:var(--atlas-text)}.atlas-home-box-white{box-shadow:0 10px 22px rgba(70,56,38,.04)}.atlas-home-box-purple{background:var(--atlas-purple);border-color:#9ca1d0;color:#fff}.atlas-home-box strong{font-size:44px;line-height:.94;font-weight:950;letter-spacing:-.07em}.atlas-home-box em{font-style:normal;font-size:17px;line-height:1.2;font-weight:900;color:inherit;opacity:.82}.atlas-home-mini-list,.atlas-home-zone-list{margin-top:auto;display:grid;gap:8px}.atlas-home-mini-list span,.atlas-home-zone-list span,.atlas-home-mini-list button{border:2px solid var(--atlas-border-soft);border-radius:999px;background:var(--atlas-cream);padding:8px 12px;color:var(--atlas-muted);font-size:16px;line-height:1.1;font-weight:900;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.atlas-home-box-purple .atlas-home-mini-list button{border-color:rgba(255,255,255,.25);background:rgba(255,255,255,.13);color:#fff}
.atlas-home-task-hero{gap:8px;padding:14px}.atlas-home-task-hero button{border:0;background:transparent;color:inherit;text-align:left}.atlas-home-primary-task{display:grid;gap:5px;width:100%;padding:0}.atlas-home-primary-task strong{font-size:clamp(24px,5.1vw,32px);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.atlas-home-primary-task em,.atlas-home-task-title{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.atlas-home-task-buttons{display:grid;gap:6px;margin-top:auto}.atlas-home-task-buttons button{min-height:34px;border:1px solid rgba(255,255,255,.24)!important;border-radius:16px!important;background:rgba(255,255,255,.12)!important;padding:6px 9px!important;display:grid;gap:2px;overflow:hidden}.atlas-home-task-buttons span,.atlas-home-task-buttons small{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;color:inherit}.atlas-home-task-buttons span{font-size:11px;font-weight:950}.atlas-home-task-buttons small{font-size:9px;font-weight:850;opacity:.78}
.atlas-task-focus-overlay{position:fixed;z-index:1000;inset:0;background:rgba(248,245,238,.98);overflow:auto}.atlas-task-focus-phone{width:min(100%,860px);margin:0 auto;min-height:100dvh;background:var(--atlas-paper);border-left:2px solid var(--atlas-border);border-right:2px solid var(--atlas-border)}.atlas-task-focus-topbar{position:sticky;top:0;z-index:2;background:var(--atlas-paper);min-height:116px;border-bottom:2px solid var(--atlas-border);padding:24px 26px;display:flex;align-items:center;justify-content:space-between}.atlas-task-focus-topbar strong{font-size:32px;font-weight:950;letter-spacing:-.05em}.atlas-task-focus-topbar button{border:2px solid var(--atlas-border);border-radius:999px;background:var(--atlas-paper);padding:18px 26px;color:var(--atlas-text);font-size:22px;font-weight:900}.atlas-task-focus-body{display:grid;gap:18px;padding:22px}.atlas-task-focus-purple{background:var(--atlas-purple);border:2px solid #9ca1d0;color:#fff;border-radius:34px;padding:24px;box-shadow:0 16px 32px rgba(86,76,145,.14)}.atlas-task-focus-kicker span{display:inline-block;border:2px solid rgba(255,255,255,.25);border-radius:999px;padding:8px 14px;font-weight:900}.atlas-task-focus-purple h2{font-size:48px;line-height:.95;margin:12px 0 8px;font-weight:950;letter-spacing:-.07em}.atlas-task-focus-purple p{font-size:21px;font-weight:900;margin:0;opacity:.9}.atlas-task-focus-section,.atlas-closeout-card,.atlas-field-log-item,.atlas-task-row{border:2px solid var(--atlas-border);border-radius:28px;background:rgba(255,253,248,.92);padding:18px}.atlas-add-form{display:grid;gap:14px}.atlas-add-form textarea,.atlas-add-form input,.atlas-add-form select{width:100%;border:2px solid var(--atlas-border);border-radius:22px;background:#fffaf4;color:var(--atlas-text);padding:16px 18px;font-size:21px;font-weight:850}.atlas-add-form textarea{min-height:120px}.atlas-zone-action,.atlas-task-play-actions button{border:2px solid var(--atlas-border);border-radius:999px;background:var(--atlas-cream);color:var(--atlas-text);padding:14px 18px;font-size:18px;font-weight:950}.atlas-task-play-actions{display:flex;gap:8px;flex-wrap:wrap}.atlas-task-play-actions-wide button{flex:1 1 120px}.atlas-empty{color:var(--atlas-muted);font-weight:850;font-size:18px}.atlas-task-row-main{width:100%;border:0;background:transparent;text-align:left;color:inherit}.atlas-task-row strong{display:block;font-size:24px;font-weight:950}.atlas-task-row span,.atlas-task-row small{display:block;color:var(--atlas-muted);font-weight:850;margin-top:4px}
.atlas-closeout-grid{display:grid;gap:14px}.atlas-closeout-card-head{display:flex;justify-content:space-between;gap:10px}.atlas-closeout-card-head strong{font-size:32px;font-weight:950;letter-spacing:-.05em}.atlas-closeout-card-head span{color:var(--atlas-muted);font-size:18px;font-weight:900}.atlas-closeout-pill-row{display:flex;gap:7px;flex-wrap:wrap}.atlas-closeout-pill-row span,.atlas-record-zone,.atlas-record-kind{border:2px solid var(--atlas-border-soft);border-radius:999px;background:var(--atlas-cream);padding:7px 10px;font-size:14px;font-weight:950}.atlas-closeout-section,.atlas-record-list{border-top:2px solid var(--atlas-border-soft);padding-top:12px;display:grid;gap:9px}.atlas-closeout-section>span,.atlas-record-list>span{color:#858bb8;letter-spacing:.14em;text-transform:uppercase;font-size:13px;font-weight:950}.atlas-closeout-section p{margin:0;color:var(--atlas-muted);font-size:20px;line-height:1.25;font-weight:850}.atlas-record-card{border:2px solid var(--atlas-border-soft);border-radius:22px;background:#fbf7ef;padding:16px;display:grid;gap:8px}.atlas-record-card-top{display:flex;justify-content:space-between;gap:8px}.atlas-record-kind{background:#eef0ff;color:#656b9c}.atlas-record-card strong{font-size:30px;line-height:1;font-weight:950;letter-spacing:-.05em}.atlas-record-card p{margin:0}.atlas-record-crop{font-size:21px;font-weight:900}.atlas-record-date,.atlas-record-note{color:var(--atlas-muted);font-size:17px;font-weight:850;line-height:1.25}.atlas-record-note{border-top:2px solid var(--atlas-border-soft);padding-top:8px}.atlas-closeout-hero{position:relative;display:grid!important;align-content:start!important;gap:10px!important;min-height:166px!important;height:auto!important;box-sizing:border-box!important;overflow:hidden!important;padding:20px!important;margin-bottom:12px!important}.atlas-closeout-hero .atlas-task-focus-kicker{display:none!important}.atlas-closeout-hero h2,.atlas-closeout-hero p{margin:0!important;padding:0!important;font-size:0!important;line-height:0!important}.atlas-closeout-hero h2:before{content:"July record";display:block;color:#fff;font-size:clamp(34px,8vw,46px);line-height:.92;font-weight:950;letter-spacing:-.07em}.atlas-closeout-hero p:before{content:"6 updates logged";display:block;color:rgba(255,255,255,.92);font-size:15px;line-height:1;font-weight:900}.atlas-closeout-hero:after{content:"Sown 3 beds · Checked 3 areas · Open 14 tasks";display:block;width:fit-content;max-width:100%;box-sizing:border-box;border:1px solid rgba(255,255,255,.28);border-radius:999px;background:rgba(255,255,255,.13);color:#fff;padding:9px 12px;font-size:12px;line-height:1.1;font-weight:950;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
@media(max-width:700px){.atlas-phone-shell{padding:0;background:#f8f5ee}.atlas-phone{border:0;border-radius:0;min-height:100dvh}.atlas-phone-top{height:110px;padding:22px}.atlas-home-grid{gap:14px;padding:14px}.atlas-home-box{min-height:242px;border-radius:26px;padding:18px}.atlas-home-box strong{font-size:34px}.atlas-home-box em{font-size:14px}.atlas-soft-badge{font-size:23px}.atlas-task-focus-body{padding:16px}.atlas-task-focus-topbar{min-height:102px;padding:20px}.atlas-task-focus-topbar strong{font-size:30px}.atlas-task-focus-topbar button{font-size:18px;padding:14px 22px}.atlas-closeout-hero{min-height:150px!important;padding:17px!important;gap:8px!important}.atlas-closeout-hero h2:before{font-size:clamp(32px,9.5vw,40px)}.atlas-closeout-hero p:before{font-size:13px}.atlas-closeout-hero:after{width:100%;font-size:10px;padding:8px 9px}.atlas-record-card strong{font-size:25px}}
@media(max-width:390px){.atlas-home-grid{gap:10px;padding:10px}.atlas-home-box{padding:14px;min-height:220px}.atlas-home-box strong{font-size:28px}.atlas-home-mini-list span,.atlas-home-zone-list span{font-size:12px;padding:7px 10px}}
`;

export const metadata: Metadata = {
  title: "Atlas · Elm Farm",
  description: "Elm Farm task hand and field registry",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <head>
        <style dangerouslySetInnerHTML={{ __html: criticalAtlasCss }} />
      </head>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
