create or replace function atlas.record_production_establishment_v1(
  p_task_id uuid,p_stands jsonb,p_action text,p_observed_date date,p_recheck_date date,p_note text,p_idempotency_key text
) returns jsonb language plpgsql security definer set search_path=pg_catalog,atlas as $$
declare
  v_today date := (now() at time zone 'America/Chicago')::date;
  v_task atlas.tasks%rowtype; v_lot atlas.production_lots%rowtype; v_gate atlas.production_transplant_gates%rowtype;
  v_key text:=nullif(btrim(p_idempotency_key),''); v_existing uuid; v_total numeric:=0; v_row record; v_stand atlas.production_field_stands%rowtype;
  v_outcome text; v_loss numeric; v_transition jsonb; v_plan_task uuid; v_harvest_gate uuid; v_owner_membership uuid;
begin
  if p_task_id is null or p_stands is null or jsonb_typeof(p_stands)<>'array' or jsonb_array_length(p_stands)=0 or p_action not in ('not_yet','established','failed') or p_observed_date is null then raise exception 'Task, stand counts, valid establishment action, and observation date are required' using errcode='22023'; end if;
  if v_key is null or length(v_key)>120 then raise exception 'A valid establishment idempotency key is required' using errcode='22023'; end if;
  if p_observed_date>v_today+1 then raise exception 'Observation date cannot be in the future' using errcode='22023'; end if;
  if p_action='not_yet' and (p_recheck_date is null or p_recheck_date<=p_observed_date) then raise exception 'Not-yet establishment requires a later recheck date' using errcode='22023'; end if;
  select * into v_task from atlas.tasks where id=p_task_id for update;
  select pl.* into v_lot from atlas.production_lot_tasks plt join atlas.production_lots pl on pl.id=plt.production_lot_id where plt.task_id=p_task_id and plt.link_role='establishment_check' limit 1 for update of pl;
  if v_task.id is null or v_lot.id is null then raise exception 'Task is not a linked production establishment check' using errcode='22023'; end if;
  select * into v_gate from atlas.production_transplant_gates where id=v_task.generated_from_id and production_lot_id=v_lot.id;
  if v_gate.id is null or v_gate.gate_status<>'transplanted' then raise exception 'Establishment check requires a completed transplant gate' using errcode='22023'; end if;
  select id into v_existing from atlas.production_lot_events where farm_id=v_lot.farm_id and idempotency_key=left(v_key||':event:establishment',160);
  if v_existing is not null then return jsonb_build_object('taskId',p_task_id,'productionLotId',v_lot.id,'action',p_action,'deduplicated',true); end if;
  if v_task.status not in ('open','blocked') then raise exception 'Establishment task is not open' using errcode='22023'; end if;
  create temporary table if not exists pg_temp.production_establishment_input(placement_id uuid primary key,plants_alive numeric not null) on commit drop;
  truncate pg_temp.production_establishment_input;
  insert into pg_temp.production_establishment_input(placement_id,plants_alive) select (x->>'placementId')::uuid,(x->>'plantsAlive')::numeric from jsonb_array_elements(p_stands) x;
  if exists(select 1 from pg_temp.production_establishment_input where plants_alive<0) then raise exception 'Living plant counts cannot be negative' using errcode='22023'; end if;
  if (select count(*) from pg_temp.production_establishment_input)<>(select count(*) from atlas.production_field_stands where production_lot_id=v_lot.id and stand_status<>'cleared') then raise exception 'Every active field stand requires one establishment count' using errcode='22023'; end if;
  if exists(select 1 from pg_temp.production_establishment_input i left join atlas.production_field_stands s on s.transplant_placement_id=i.placement_id and s.production_lot_id=v_lot.id where s.id is null or i.plants_alive>s.current_plants) then raise exception 'Establishment counts must match this lot and cannot exceed the prior living count' using errcode='22023'; end if;
  select sum(plants_alive) into v_total from pg_temp.production_establishment_input;
  if p_action='established' and v_total<=0 then raise exception 'Established production requires living plants' using errcode='22023'; end if;
  if p_action='failed' and v_total<>0 then raise exception 'Failed establishment must record zero living plants' using errcode='22023'; end if;
  for v_row in select * from pg_temp.production_establishment_input loop
    select * into v_stand from atlas.production_field_stands where transplant_placement_id=v_row.placement_id for update;
    v_loss:=v_stand.current_plants-v_row.plants_alive;
    v_outcome:=case when v_row.plants_alive=0 then 'failed' when v_loss>0 then 'partial_loss' when p_action='established' then 'established' else 'not_yet' end;
    insert into atlas.production_field_observations(farm_id,production_lot_id,task_id,object_id,crop_cycle_id,observation_type,outcome,observed_date,quantity,unit,note,idempotency_key,metadata)
    values(v_lot.farm_id,v_lot.id,p_task_id,v_stand.object_id,v_stand.crop_cycle_id,'establishment',v_outcome,p_observed_date,v_row.plants_alive,'plants',p_note,left(v_key||':stand:'||v_stand.id::text,160),jsonb_build_object('field_stand_id',v_stand.id,'transplant_placement_id',v_stand.transplant_placement_id,'plants_transplanted',v_stand.plants_transplanted,'plants_lost',v_loss,'next_check_date',case when p_action='not_yet' then p_recheck_date else null end,'confidence','counted'));
    update atlas.production_field_stands set current_plants=v_row.plants_alive,total_losses=plants_transplanted-v_row.plants_alive,last_observed_date=p_observed_date,stand_status=case when v_row.plants_alive=0 then 'failed' when p_action='established' then 'established' else 'establishing' end,established_date=case when p_action='established' and v_row.plants_alive>0 then p_observed_date else established_date end,metadata=metadata||jsonb_build_object('last_establishment_action',p_action),updated_at=now() where id=v_stand.id;
    update atlas.crop_cycles set cycle_state=case when v_row.plants_alive=0 then 'failed' when p_action='established' then 'established' else 'establishment' end,lifecycle_status=case when v_row.plants_alive=0 then 'archived' else 'active' end,coverage_kind='living_plants',coverage_amount=v_row.plants_alive,coverage_unit='plants',metadata=metadata||jsonb_build_object('establishment_observed_date',p_observed_date,'establishment_action',p_action),updated_at=now() where id=v_stand.crop_cycle_id;
    update atlas.object_state set life_status=case when v_row.plants_alive=0 then 'failed' when p_action='established' then 'growing' else life_status end,last_checked_at=p_observed_date,last_touched_at=p_observed_date,metadata=metadata||jsonb_build_object('production_lot_id',v_lot.id,'living_plants',v_row.plants_alive,'establishment_action',p_action),updated_at=now() where object_id=v_stand.object_id;
  end loop;
  update atlas.production_lots set current_quantity=v_total,current_unit='plants',current_stage=case when p_action='established' then 'field_care' when p_action='failed' then 'establishment_failed' else 'establishment' end,lifecycle_status=case when p_action='failed' then 'failed' else 'active' end,metadata=metadata||jsonb_build_object('last_biological_event',case when p_action='established' then 'established' when p_action='failed' then 'establishment_failed' else 'establishment_not_yet' end,'establishment_observed_date',p_observed_date,'living_plants',v_total),updated_at=now() where id=v_lot.id;
  insert into atlas.production_lot_events(farm_id,production_lot_id,event_type,event_date,quantity,unit,task_id,note,source,idempotency_key,metadata)
  values(v_lot.farm_id,v_lot.id,case when p_action='established' then 'established' when p_action='failed' then 'establishment_failed' else 'establishment_not_yet' end,p_observed_date,v_total,'plants',p_task_id,p_note,'production_stage_engine',left(v_key||':event:establishment',160),jsonb_build_object('transplant_gate_id',v_gate.id,'stand_counts',p_stands));
  if p_action='not_yet' then
    v_transition:=atlas.record_task_transition_v1_internal(p_task_id,'rescheduled',left(v_key||':task:not-yet',160),p_recheck_date,coalesce(nullif(btrim(p_note),''),'Transplants are not fully established yet.'),'Establishment not complete.','observe','production_lot',jsonb_build_object('production_lot_id',v_lot.id,'living_plants',v_total,'next_check_date',p_recheck_date,'stand_counts',p_stands),null);
    return jsonb_build_object('taskId',p_task_id,'productionLotId',v_lot.id,'action','not_yet','livingPlants',v_total,'nextDate',p_recheck_date,'deduplicated',false);
  end if;
  v_transition:=atlas.record_task_transition_v1_internal(p_task_id,'done',left(v_key||':task:done',160),null,coalesce(nullif(btrim(p_note),''),case when p_action='failed' then 'No transplanted plants established.' else v_total::text||' plants established.' end),null,'observe','production_lot',jsonb_build_object('production_lot_id',v_lot.id,'establishment_action',p_action,'living_plants',v_total,'stand_counts',p_stands),null);
  insert into atlas.production_harvest_readiness_gates(farm_id,production_lot_id,plants_alive,gate_status,blocker_text,metadata)
  values(v_lot.farm_id,v_lot.id,v_total,case when p_action='failed' then 'failed' else 'waiting_field_plan' end,case when p_action='failed' then 'No living plants remain after establishment.' else 'Harvest timing and crop-care policy are not confirmed.' end,jsonb_build_object('transplant_gate_id',v_gate.id,'establishment_task_id',p_task_id))
  on conflict(production_lot_id) do update set plants_alive=excluded.plants_alive,gate_status=excluded.gate_status,blocker_text=excluded.blocker_text,metadata=atlas.production_harvest_readiness_gates.metadata||excluded.metadata,updated_at=now() returning id into v_harvest_gate;
  if p_action='failed' then
    select id into v_owner_membership from atlas.farm_memberships where farm_id=v_lot.farm_id and active and role='owner' order by created_at limit 1;
    insert into atlas.tasks(farm_id,title,task_type,status,priority,due_date,generated_from,generated_from_id,note,metadata,action_key,work_class,task_series_key,engine_instance_key,visibility_scope,assigned_membership_id)
    values(v_lot.farm_id,'Owner — Decide next step after failed establishment — '||v_lot.lot_label,'owner_decision','open','high',p_observed_date,'production_harvest_gate',v_harvest_gate,'The entire transplanted cohort was recorded as lost. Decide whether to replace, reseed, or close the production lot.',jsonb_build_object('task_key','production_establishment_failure_'||v_harvest_gate::text,'owner_task',true,'production_lot_id',v_lot.id,'production_harvest_gate_id',v_harvest_gate,'living_plants',0,'display_action','Decide','display_subject',v_lot.lot_label||' establishment failure','display_detail','0 plants remain','collection_zone','Owner'),'decide','light','production-lot:'||v_lot.stable_key||':establishment-failure','production-establishment-failure:'||v_harvest_gate::text,'owner',v_owner_membership) returning id into v_plan_task;
    insert into atlas.production_lot_tasks(production_lot_id,task_id,link_role,source,metadata) values(v_lot.id,v_plan_task,'establishment_failure_decision','production_stage_engine',jsonb_build_object('harvest_gate_id',v_harvest_gate));
    return jsonb_build_object('taskId',p_task_id,'productionLotId',v_lot.id,'action','failed','livingPlants',0,'decisionTaskId',v_plan_task,'deduplicated',false);
  end if;
  select id into v_owner_membership from atlas.farm_memberships where farm_id=v_lot.farm_id and active and role='owner' order by created_at limit 1;
  insert into atlas.tasks(farm_id,title,task_type,status,priority,due_date,generated_from,generated_from_id,note,metadata,action_key,work_class,task_series_key,engine_instance_key,visibility_scope,assigned_membership_id)
  values(v_lot.farm_id,'Owner — Set field-care + harvest plan — '||v_lot.lot_label,'production_field_plan','open','high',p_observed_date,'production_harvest_gate',v_harvest_gate,'Confirm harvest-watch dates and whether watering, weeding, pinching, support, or fertility must block harvest readiness.',jsonb_build_object('task_key','production_field_plan_'||v_harvest_gate::text,'owner_task',true,'production_lot_id',v_lot.id,'production_harvest_gate_id',v_harvest_gate,'living_plants',v_total,'missing_facts',jsonb_build_array('harvest_watch_start','harvest_watch_end','watering_policy','weeding_policy','pinching_policy'),'display_action','Plan','display_subject',v_lot.lot_label||' field care','display_detail',v_total::text||' established plants','collection_zone','Owner'),'plan','light','production-lot:'||v_lot.stable_key||':field-plan','production-field-plan:'||v_harvest_gate::text,'owner',v_owner_membership) returning id into v_plan_task;
  update atlas.production_harvest_readiness_gates set field_plan_task_id=v_plan_task,updated_at=now() where id=v_harvest_gate;
  insert into atlas.production_lot_tasks(production_lot_id,task_id,link_role,source,metadata) values(v_lot.id,v_plan_task,'field_plan_decision','production_stage_engine',jsonb_build_object('harvest_gate_id',v_harvest_gate));
  insert into atlas.task_objects(task_id,object_id,role) select v_plan_task,object_id,'field_stand' from atlas.production_field_stands where production_lot_id=v_lot.id and current_plants>0 on conflict do nothing;
  insert into atlas.task_crop_cycles(task_id,crop_cycle_id,role,confidence,source,metadata) select v_plan_task,crop_cycle_id,'plans','confirmed','production_stage_engine',jsonb_build_object('harvest_gate_id',v_harvest_gate) from atlas.production_field_stands where production_lot_id=v_lot.id and current_plants>0 on conflict do nothing;
  return jsonb_build_object('taskId',p_task_id,'productionLotId',v_lot.id,'action','established','livingPlants',v_total,'fieldPlanTaskId',v_plan_task,'harvestGateId',v_harvest_gate,'deduplicated',false);
end; $$;