insert into atlas.projects (
  farm_id,
  organization_id,
  stable_key,
  title,
  status,
  workstream,
  project_kind,
  portfolio_type,
  reality_state,
  health_status,
  goal_text,
  outcome_text,
  current_milestone,
  target_date,
  last_movement_at,
  metadata
)
values (
  '6a503d9f-4008-4ddb-b3f0-cc6ab825dc9f'::uuid,
  '818b9a23-65e9-4198-b86c-9496ba548642'::uuid,
  'arise_at_elm',
  'Arise at Elm',
  'active',
  'hospitality',
  'farm',
  'program',
  'making_real',
  'moving',
  'Create a repeatable early-morning movement program at Elm that gives working adults a consistent place to strengthen their bodies, build community, and begin the day ready for their work.',
  'Elm runs a durable 12-week dawn movement season twice weekly at a fixed 6:00 a.m. time, using the flower-row sunrise corridor outdoors and the Detached Garage as weather backup, with an instructor partnership that brings both Elm’s audience and the instructor’s audience into one recurring community.',
  'Identify and secure the first movement instructor, then define the Fall 2026 launch roster and registration offering.',
  '2026-09-01'::date,
  now(),
  jsonb_build_object(
    'created_from','owner_direction_20260813',
    'public_name','Arise at Elm',
    'canonical_function','arise → strengthen the body → enter the day fit for work',
    'schedule',jsonb_build_object('weeks',12,'days',jsonb_build_array('Tuesday','Thursday'),'time_local','06:00','classes_total',24,'timezone','America/Chicago'),
    'pricing',jsonb_build_object('season_price_usd',240,'revenue_split',jsonb_build_object('elm_percent',50,'instructor_percent',50),'drop_in_model',false),
    'instructor_status','unresolved',
    'movement_modality','unresolved',
    'outdoor_location','Between the BB and BW flower rows, facing sunrise through the trees',
    'weather_backup','Detached Garage',
    'elm_supplies',jsonb_build_array('short, even mowed grass','Bluetooth speaker','weather-backup exercise space','registration and program administration'),
    'participant_supplies',jsonb_build_array('exercise mat','water'),
    'registration_model','12-week season membership rather than pay-per-attendance'
  )
)
on conflict (organization_id, stable_key) do update set
  farm_id = excluded.farm_id,
  title = excluded.title,
  status = excluded.status,
  workstream = excluded.workstream,
  project_kind = excluded.project_kind,
  portfolio_type = excluded.portfolio_type,
  reality_state = excluded.reality_state,
  health_status = excluded.health_status,
  goal_text = excluded.goal_text,
  outcome_text = excluded.outcome_text,
  current_milestone = excluded.current_milestone,
  target_date = excluded.target_date,
  last_movement_at = now(),
  metadata = excluded.metadata,
  updated_at = now();