insert into atlas.authenticated_rpc_registry(
  signature,classification,confidence,review_status,authenticated_execute_expected,security_definer_expected,service_execute_expected,caller_count,policy_reference_count,evidence,reviewed_at
) values
('atlas.record_flower_demand_order_for_member_v1(uuid, uuid, text, text, text, date, text, time without time zone, jsonb, text, text)','app_endpoint','verified','active',true,true,true,1,0,jsonb_build_object('purpose','Record dated flower demand independently of Ready supply','boundary','active farm membership required; Farm Hand may record demand but does not thereby claim supply or schedule fulfillment','demandTruth','requested/committed demand can exist while Ready inventory is zero','inventoryTruth','no Ready lot is referenced or claimed','clockTruth','demand recording creates no Worker Day task'),now()),
('atlas.owner_operator_record_flower_demand_order_v1(uuid, uuid, text, text, text, date, text, time without time zone, jsonb, text, text)','owner_admin_endpoint','verified','active',true,true,true,1,0,jsonb_build_object('purpose','Record the same independent flower demand while Owner operates as an effective farm membership','boundary','owner_operator_context_v1 resolves the effective membership and farm scope','inventoryTruth','operator mode cannot manufacture Ready inventory or sale truth','clockTruth','operator mode does not convert demand entry into Principal or Worker scheduling'),now()),
('atlas.cancel_flower_demand_order_for_member_v1(uuid, uuid, text, text, text)','app_endpoint','verified','active',true,true,true,1,0,jsonb_build_object('purpose','Append a cancellation fact for independent flower demand','boundary','active farm membership; Farm Hand may cancel only demand they recorded','historyTruth','original demand and lines remain immutable','inventoryTruth','cancellation does not reverse or create any Ready inventory claim'),now()),
('atlas.owner_operator_cancel_flower_demand_order_v1(uuid, uuid, text, text, text)','owner_admin_endpoint','verified','active',true,true,true,1,0,jsonb_build_object('purpose','Append the same independent-demand cancellation while Owner operates as an effective farm membership','boundary','owner_operator_context_v1 resolves effective membership and farm scope','historyTruth','original demand stays immutable'),now()),
('atlas.record_flower_standing_order_for_member_v1(uuid, uuid, text, text, text, time without time zone, date, date, integer, jsonb, text, text)','app_endpoint','verified','active',true,true,true,1,0,jsonb_build_object('purpose','Record an immutable recurring flower-demand definition independent of supply','boundary','Owner or Manager authority required','standingTruth','weekly recurrence is anchored to a first due date and may end by date or cancellation event','inventoryTruth','standing demand claims no Ready inventory','clockTruth','standing-order definition does not directly schedule worker time'),now()),
('atlas.owner_operator_record_flower_standing_order_v1(uuid, uuid, text, text, text, time without time zone, date, date, integer, jsonb, text, text)','owner_admin_endpoint','verified','active',true,true,true,1,0,jsonb_build_object('purpose','Record a recurring flower-demand definition in Owner operator mode','boundary','effective role must still have Owner or Manager commercial authority','inventoryTruth','operator mode cannot manufacture supply or sale truth','clockTruth','no Worker Day or Principal work is created by definition alone'),now()),
('atlas.cancel_flower_standing_order_for_member_v1(uuid, uuid, text, text, text)','app_endpoint','verified','active',true,true,true,1,0,jsonb_build_object('purpose','Append a cancellation fact that ends a standing flower-demand definition','boundary','Owner or Manager authority required','historyTruth','standing definition and product lines remain immutable'),now()),
('atlas.owner_operator_cancel_flower_standing_order_v1(uuid, uuid, text, text, text)','owner_admin_endpoint','verified','active',true,true,true,1,0,jsonb_build_object('purpose','Append standing-demand cancellation in Owner operator mode','boundary','effective role must retain Owner or Manager authority','historyTruth','cancellation is append-only and preserves prior recurring-demand truth'),now())
on conflict(signature) do update set
  classification=excluded.classification,
  confidence=excluded.confidence,
  review_status=excluded.review_status,
  authenticated_execute_expected=excluded.authenticated_execute_expected,
  security_definer_expected=excluded.security_definer_expected,
  service_execute_expected=excluded.service_execute_expected,
  caller_count=excluded.caller_count,
  policy_reference_count=excluded.policy_reference_count,
  evidence=excluded.evidence,
  reviewed_at=excluded.reviewed_at;