do $migration$
declare
  v_elm uuid := '6a503d9f-4008-4ddb-b3f0-cc6ab825dc9f'::uuid;
  v_finish_elm uuid := '68dafbf0-9923-43fb-a6ac-8b6dee57730c'::uuid;
  v_arrival uuid := '423232fd-544a-4927-9c00-7849d49a148b'::uuid;
  v_horizon_profile uuid := 'e47dffd4-4c68-401b-bb3a-70b6e6e781dd'::uuid;
  v_orange_profile uuid := '769f6f3f-fcaa-48c6-9869-4629208d0b4d'::uuid;
begin
  if not exists(select 1 from atlas.farms where id=v_elm and stable_key='elm_farm') then raise exception 'Elm Farm identity drifted.'; end if;

  update atlas.tasks set metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('why_now','Daily animal care keeps the flock fed, watered, and eggs collected.','state_effect','Chickens are fed, the water bucket is refreshed, and eggs are gathered.','execution_do','Complete the chicken chore','execution_how',jsonb_build_array('Give 4 scoops of feed.','Refresh the water bucket.','Gather eggs.'),'execution_done_when','Feed, water, and egg gathering are complete.'),updated_at=now() where id='033d6d9e-72d6-4de9-9e0a-a7008ccc77ae' and farm_id=v_elm and title='Chicken Chore';
  if not found then raise exception 'Chicken Chore task drifted.'; end if;

  update atlas.tasks set metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('structured_result_required',true,'why_now','Continue the school and preschool enrollment paperwork.','state_effect','The next required enrollment form is completed.','execution_do','Fill out the next enrollment form','execution_how',jsonb_build_array('Complete the next required school or preschool enrollment form.'),'execution_done_when','The next required form is completed.'),updated_at=now() where id='7628fa29-d019-4d89-baa3-3535ed172f7f' and farm_id=v_elm and title='School and Preschool Enrollment';
  if not found then raise exception 'Enrollment task drifted.'; end if;

  update atlas.tasks set metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('why_now','Clean one visible garage face as a bounded exterior-finish move.','state_effect','One detached-garage face is visibly cleaner without forcing water into openings or trim.','execution_do','Gently pressure wash one detached-garage face','execution_how',jsonb_build_array('Use a wide fan and low pressure.','Keep the wand moving.','Avoid forcing water into doors, windows, and trim joints.'),'execution_done_when','One garage face is gently cleaned.'),updated_at=now() where id='ba193090-b6c8-49c3-9110-046216a7a091' and farm_id=v_elm and title='Gently Pressure Wash Detached Garage Face';
  if not found then raise exception 'Detached garage wash task drifted.'; end if;

  update atlas.tasks set metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('structured_result_required',true,'why_now','Move the Shasta daisy seedlings out of the dense nursery-box stage and into individual plugs.','state_effect','130 Shasta daisy seedlings are potted into 200-cell plugs for continued Grow Room care.','execution_do','Pot up Shasta daisy','execution_place','Grow Room · 200-cell Pot Up','execution_how',jsonb_build_array('Pot up tray 1 into individual 200-cell plugs.','Handle 130 seedlings in this move.'),'execution_done_when','Tray 1 · 130 Shasta daisy seedlings are potted up.'),updated_at=now() where id='3340d49f-c27c-4395-88c9-6b7bca4fd857' and farm_id=v_elm and title='Shasta daisy — tray 1 — 130';
  if not found then raise exception 'Shasta pot-up task drifted.'; end if;

  update atlas.tasks set metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('structured_result_required',true,'why_now','Move the tiny feverfew and oregano seedlings into individual plugs while keeping the oregano in Grow Room grow-out.','state_effect','The Tetra feverfew and oregano seedlings are potted up for continued Grow Room growth; no Main Garden transplant is claimed.','execution_do','Pot up Tetra feverfew + oregano','execution_place','Grow Room · 200-cell Pot Up','execution_how',jsonb_build_array('Pot the tiny seedlings into individual 200-cell plugs.','Include the two Greek oregano pots and two Italian oregano pots sown July 14.','Do not transplant oregano to the Main Garden yet.','Keep the oregano growing out until it is established enough for later garden planting.'),'execution_done_when','Tray 1 · 185 feverfew + oregano seedlings are potted up for Grow Room grow-out.'),updated_at=now() where id='5b6dcc58-c002-4aff-8ebb-0a27e3b0034a' and farm_id=v_elm and title='Tetra feverfew + oregano — tray 1 — 185';
  if not found then raise exception 'Feverfew/oregano pot-up task drifted.'; end if;

  update atlas.tasks set metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('structured_result_required',true,'why_now','Move this Sweet William batch into individual plugs for continued Grow Room care.','state_effect','480 Sweet William seedlings are potted into three trays for continued Grow Room growth.','execution_do','Pot up Sweet William','execution_place','Grow Room · 200-cell Pot Up','execution_how',jsonb_build_array('Pot up 3 trays totaling 480 plants.'),'execution_done_when','All 3 Sweet William trays are potted up.'),updated_at=now() where id='6ee83d68-4029-4bf1-8cd8-3d35b4b28578' and farm_id=v_elm and title='Pot up · Sweet William';
  if not found then raise exception 'Sweet William pot-up task drifted.'; end if;

  update atlas.tasks set metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('why_now','The previous check found no emergence, so this is another direct observation rather than an assumed germination date.','state_effect','Barn Bed 8 gets a current germination observation; if emergence is still absent, the check can move again.','execution_do','Check ProCut Horizon germination','execution_place','Barn Bed 8','execution_done_when','A current germination result is recorded.'),updated_at=now() where id='365bfba7-e2d6-4a66-b7c8-6cd37f3ccbf1' and farm_id=v_elm and task_type='germination_check';
  if not found then raise exception 'Barn Bed 8 germination task drifted.'; end if;

  update atlas.tasks set unlock_text=null,metadata=(coalesce(metadata,'{}'::jsonb)-'dependent_task_ids')||jsonb_build_object('why_now','Reduce weed pressure in MG2 now so the bed is ready when the oregano is actually established enough to plant.','state_effect','MG2 is cleared and held ready for a later planting move; this task does not claim that the oregano is ready yet.','execution_done_when','The current MG2 weeding pass is recorded through the Weed Card.','stale_oregano_unlock_removed_at',now(),'stale_oregano_unlock_reason','The current Grow Room oregano task explicitly requires more grow-out before Main Garden planting.'),updated_at=now() where id='95dd62bd-44ec-410d-b186-21150e434b29' and farm_id=v_elm and title='Weed MG2';
  if not found then raise exception 'MG2 weed task drifted.'; end if;

  update atlas.tasks set metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('why_now','Check whether the Fall kale mix has reached transplant-ready condition instead of advancing it by date alone.','state_effect','A counted readiness result decides whether the kale can move forward or remains in Grow Room care.','execution_done_when','A transplant-readiness result is recorded.'),updated_at=now() where id='f56311af-dacb-4cd6-be14-d2a95d0579de' and farm_id=v_elm and task_type='transplant_readiness';
  if not found then raise exception 'Fall kale readiness task drifted.'; end if;

  update atlas.tasks set metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('structured_result_required',true,'why_now','Make an explicit decision about the grey couch so it stops remaining unresolved garage clutter.','state_effect','The couch has a recorded disposition and any selected follow-up move can be created from that decision.'),updated_at=now() where id='32fa8896-f51b-42b3-9918-00e4f3a9713b' and farm_id=v_elm and metadata->>'task_style'='decision_selector';
  if not found then raise exception 'Grey couch decision task drifted.'; end if;

  update atlas.tasks set metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('structured_result_required',true,'why_now','Use one Grow Room Care doorway for the open round instead of making Anna rediscover the same adopted work elsewhere.','state_effect','Every request adopted into this Grow Room round is resolved before the round closes.','execution_done_when','Every Grow Room round request is resolved and the round is finished.'),updated_at=now() where id='7e0f572e-07bf-464f-9791-9dff75ca29f4' and farm_id=v_elm and task_type='grow_room_care';
  if not found then raise exception 'Current Grow Room Care task drifted.'; end if;

  update atlas.tasks set metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('why_now','Refresh the coop bedding on its five-week maintenance cycle.','state_effect','Chicken bedding is 5 inches deep, and the removed bedding becomes weed suppression in the named beds.','execution_do','Refresh chicken bedding to 5 inches','execution_place','Chicken shed + Red Barn bedding supply','execution_how',jsonb_build_array('Bring fresh bedding from the Red Barn.','Refresh bedding to 5 inches deep across the whole chicken shed.','Put the old bedding in the FM small bed and the 3rd arch beds of the Curve Garden as weed suppression.'),'execution_done_when','The whole chicken shed has 5 inches of fresh bedding and the old bedding is placed in the specified beds.'),updated_at=now() where id='89c3c884-8f4f-4a04-b961-bde1741bbe00' and farm_id=v_elm and title='Refresh Chicken Bedding to 5″';
  if not found then raise exception 'Chicken bedding task drifted.'; end if;

  update atlas.tasks set metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('crop_label','Sunflower','variety','ProCut Horizon','crop_profile_id',v_horizon_profile,'crop_profile_stable_key','sunflower_procut_horizon','why_now','Berry Walk Beds 7 and 8 are available for a new Horizon succession after browsing damage.','state_effect','BW7 and BW8 become active ProCut Horizon sowings, with germination checks generated from the recorded sow date.','execution_do','Sow ProCut Horizon','execution_place','Berry Walk Flower Rows · Beds 7–8','execution_how',jsonb_build_array('Use 3 rows per bed at 4-inch spacing.','Protect the new succession from deer if a practical method is available.'),'execution_done_when','Berry Walk Beds 7 and 8 are sown.'),updated_at=now() where id='3b0f91e6-d421-433e-b345-4d1a3ae1068a' and farm_id=v_elm and title='Sow ProCut Horizon — BW7 + BW8';
  if not found then raise exception 'Horizon sow task drifted.'; end if;

  update atlas.tasks set metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('crop_label','Sunflower','variety','ProCut Orange','crop_profile_id',v_orange_profile,'crop_profile_stable_key','sunflower_procut_orange','why_now','Berry Walk Beds 4 and 5 can be reset from the browsed stand into the new Orange succession.','state_effect','BW4 and BW5 become active ProCut Orange sowings, with germination checks generated from the recorded sow date.','execution_do','Sow ProCut Orange','execution_place','Berry Walk Flower Rows · Beds 4–5','execution_how',jsonb_build_array('Clear only what physically interferes with sowing.','Use the beds for the new ProCut Orange succession.'),'execution_done_when','Berry Walk Beds 4 and 5 are sown.'),updated_at=now() where id='8a29b838-3dff-4c97-94aa-b2064758e1a4' and farm_id=v_elm and title='Sow ProCut Orange — BW4 + BW5';
  if not found then raise exception 'Orange sow task drifted.'; end if;

  perform atlas.reconcile_sowing_bed_subtasks_v1('3b0f91e6-d421-433e-b345-4d1a3ae1068a');
  perform atlas.reconcile_sowing_bed_subtasks_v1('8a29b838-3dff-4c97-94aa-b2064758e1a4');

  update atlas.tasks set metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('why_now','Clean the mildewed siding behind the spirea without damaging the shrubs.','state_effect','The visible garage siding behind the spirea is cleaner while the stems, roots, and soil are protected.','execution_do','Gently pressure wash behind the garage spirea','execution_how',jsonb_build_array('Use angles and distance that protect the shrubs.','Do not blast the stems, roots, or soil.'),'execution_done_when','The mildewed siding behind the spirea is gently cleaned without shrub damage.'),updated_at=now() where id='30206358-13eb-4729-b371-c53fbb2ba877' and farm_id=v_elm and title='Gently Pressure Wash Behind the Garage Spirea';
  if not found then raise exception 'Spirea pressure-wash task drifted.'; end if;

  update atlas.tasks set metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('why_now','Charge the mower batteries Tuesday so the push-mower routes coming due Wednesday are not blocked by equipment.','state_effect','The DeWalt mower batteries are charged and ready for Wednesday mowing.','execution_do','Charge the DeWalt mower batteries','execution_how',jsonb_build_array('Plug in the DeWalt mower batteries.'),'execution_done_when','The mower batteries are plugged in and charging for Wednesday mowing.'),updated_at=now() where id='3da877e2-3c39-416c-88ac-fecc3f126a8a' and farm_id=v_elm and title='Charge DeWalt Batteries for Mowing';
  if not found then raise exception 'Battery charging task drifted.'; end if;

  update atlas.tasks set metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('structured_result_required',true,'why_now','Prepare Karianne’s garden Tuesday so Thursday morning can be a clean harvest for the ticketed bouquet bar.','state_effect','Karianne’s garden is deadheaded and staged for Thursday morning harvest; the linked harvest and social moves can proceed.','execution_do','Prepare Karianne’s garden for Thursday harvest','execution_place','19395 Highway HH, Lebanon, MO 65536','execution_how',jsonb_build_array('Load the saw, air compressor, and regular metal rake with wood handle into your vehicle.','Take 5 black florist buckets.','Drive to Karianne’s garden.','Harvest and deadhead the garden so it is prepared for Thursday morning harvest.'),'execution_done_when','Karianne’s garden is deadheaded and ready for Thursday morning bouquet-bar harvest.'),updated_at=now() where id='beaa7d82-6434-4285-a8b8-6b2a3ecea6cb' and farm_id=v_elm and replace(title,'’','''')='Prepare Karianne''s garden for Thursday bouquet-bar harvest';
  if not found then raise exception 'Karianne task drifted.'; end if;

  update atlas.tasks set metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('why_now','Lighting is one of the remaining event-readiness moves before the Thursday evening bouquet bar.','state_effect','The conference room and porches have their intended café/solar lighting ready for evening use.','execution_do','Hang conference-room café lights and porch solar lights','execution_how',jsonb_build_array('Hang the café lights in the conference room.','Put the solar string lights on the porches.','Position the solar lights so they can charge and work for the evening.'),'execution_done_when','Conference-room café lights are hung and porch solar lights are positioned for evening use.'),updated_at=now() where id='a8e1a565-ffbd-46f2-8846-c27b30b29ac2' and farm_id=v_elm and title='Hang conference-room café lights + porch solar lights';
  if not found then raise exception 'Lighting task drifted.'; end if;

  insert into atlas.project_task_links(project_id,task_id,link_role,sort_order,source,metadata) values
    (v_finish_elm,'ba193090-b6c8-49c3-9110-046216a7a091','advances',100,'anna_day_task_semantics_20260811',jsonb_build_object('mapping','visible_exterior_finish')),
    (v_arrival,'ba193090-b6c8-49c3-9110-046216a7a091','advances',100,'anna_day_task_semantics_20260811',jsonb_build_object('mapping','visible_exterior_finish')),
    (v_finish_elm,'30206358-13eb-4729-b371-c53fbb2ba877','advances',100,'anna_day_task_semantics_20260811',jsonb_build_object('mapping','visible_exterior_finish')),
    (v_arrival,'30206358-13eb-4729-b371-c53fbb2ba877','advances',100,'anna_day_task_semantics_20260811',jsonb_build_object('mapping','visible_exterior_finish')),
    (v_finish_elm,'32fa8896-f51b-42b3-9918-00e4f3a9713b','advances',100,'anna_day_task_semantics_20260811',jsonb_build_object('mapping','finish_elm_clutter_decision'))
  on conflict(project_id,task_id) do nothing;

  update atlas.tasks set status='archived',metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('archived_reason','Superseded by canonical mowing Clock after a later physical mowing result.','superseded_by_task_id','329b97cb-ff77-4e8a-8c2b-f4e5606fe0fd','superseded_by_rhythm_state_id','683e3b87-ad15-4fc1-86f7-f1ba1dd2cb75','superseded_at',now()),updated_at=now()
  where id='ef322175-935c-4a7c-8ae3-ed7229e9fbe8' and farm_id=v_elm and title='Mowing — Follow Me Paths + Edges' and status='open' and coalesce(metadata->>'clock_managed','false')<>'true'
    and exists(select 1 from atlas.mowing_events me where me.object_id='a7432c98-9a97-4b02-9f52-f0bc0ddb631c' and me.outcome='mowed_full' and me.observed_at::date>'2026-08-04');
  if not found then raise exception 'Legacy Follow Me mowing task was not safely superseded.'; end if;
end;
$migration$;
