create or replace function atlas.record_production_field_care_v1(
  p_task_id uuid,p_action text,p_results jsonb,p_care_date date,p_note text,p_idempotency_key text
) returns jsonb language plpgsql security definer set search_path=pg_catalog,atlas as $$
declare
  v_today date:=(now() at time zone 'America/Chicago')::date;v_task atlas.tasks%rowtype;v_lot atlas.production_lots%rowtype;v_policy atlas.production_care_policies%rowtype;
  v_expected_role text;v_key text:=nullif(btrim(p_idempotency_key),'');v_field_log uuid;v_transition jsonb;v_gate jsonb;
  v_row record;v_state atlas.production_field_care_state%rowtype;v_stand atlas.production_field_stands%rowtype;v_object atlas.growing_objects%rowtype;
  v_total numeric;v_new_count numeric;v_observation_id uuid;v_next_due date;v_event_type text;
begin
  if p_task_id is null or p_action not in ('water','weed','pinch','support','fertility') or p_care_date is null or p_results is null or jsonb_typeof(p_results)<>'array' or jsonb_array_length(p_results)=0 then raise exception 'Task, supported care action, date, and per-bed results are required' using errcode='22023';end if;
  if v_key is null or length(v_key)>120 then raise exception 'A valid field-care idempotency key is required' using errcode='22023';end if;
  if p_care_date>v_today+1 then raise exception 'Care date cannot be in the future' using errcode='22023';end if;
  select * into v_task from atlas.tasks where id=p_task_id for update;
  v_expected_role:=case p_action when 'water' then 'water_care' when 'weed' then 'weed_care' when 'pinch' then 'pinch_care' when 'support' then 'support_care' else 'fertility_care' end;
  select pl.* into v_lot from atlas.production_lot_tasks plt join atlas.production_lots pl on pl.id=plt.production_lot_id where plt.task_id=p_task_id and plt.link_role=v_expected_role limit 1 for update of pl;
  if v_task.id is null or v_lot.id is null then raise exception 'Task is not linked to this production field-care action' using errcode='22023';end if;
  select * into v_policy from atlas.production_care_policies where production_lot_id=v_lot.id and care_kind=case p_action when 'water' then 'watering' when 'weed' then 'weeding' when 'pinch' then 'pinching' else p_action end for update;
  if v_policy.id is null then raise exception 'Field-care task is missing its explicit Owner policy' using errcode='22023';end if;
  if exists(select 1 from atlas.field_logs where farm_id=v_lot.farm_id and idempotency_key=left(v_key||':field-log',160)) then return jsonb_build_object('taskId',p_task_id,'productionLotId',v_lot.id,'deduplicated',true);end if;
  if v_task.status not in ('open','blocked') then raise exception 'Field-care task is not open' using errcode='22023';end if;
  create temporary table if not exists pg_temp.production_care_input(object_id uuid primary key,plants_alive numeric) on commit drop;
  truncate pg_temp.production_care_input;
  insert into pg_temp.production_care_input(object_id,plants_alive) select (x->>'objectId')::uuid,case when nullif(x->>'plantsAlive','') is null then null else (x->>'plantsAlive')::numeric end from jsonb_array_elements(p_results) x;
  if (select count(*) from pg_temp.production_care_input)<>(select count(*) from atlas.task_objects where task_id=p_task_id) then raise exception 'Every bed linked to this care task must be confirmed' using errcode='22023';end if;
  if exists(select 1 from pg_temp.production_care_input i left join atlas.task_objects t on t.task_id=p_task_id and t.object_id=i.object_id left join atlas.production_field_care_state s on s.production_lot_id=v_lot.id and s.object_id=i.object_id left join atlas.production_field_stands fs on fs.id=s.field_stand_id where t.object_id is null or s.id is null or fs.id is null or coalesce(i.plants_alive,fs.current_plants)<0 or coalesce(i.plants_alive,fs.current_plants)>fs.current_plants) then raise exception 'Care results must use linked living stands and cannot increase the plant count' using errcode='22023';end if;
  insert into atlas.field_logs(farm_id,log_date,action_types,summary_sentence,note,created_by,source,idempotency_key,metadata)
  values(v_lot.farm_id,p_care_date,array[p_action,'production_field_care'],'Completed '||p_action||' care for '||v_lot.lot_label,p_note,'production_stage_engine','production_stage_engine',left(v_key||':field-log',160),jsonb_build_object('production_lot_id',v_lot.id,'care_policy_id',v_policy.id,'action',p_action,'results',p_results)) returning id into v_field_log;
  for v_row in select * from pg_temp.production_care_input loop
    select * into v_state from atlas.production_field_care_state where production_lot_id=v_lot.id and object_id=v_row.object_id for update;
    select * into v_stand from atlas.production_field_stands where id=v_state.field_stand_id for update;
    select * into v_object from atlas.growing_objects where id=v_row.object_id;
    v_new_count:=coalesce(v_row.plants_alive,v_stand.current_plants);
    update atlas.production_field_stands set current_plants=v_new_count,total_losses=plants_transplanted-v_new_count,last_observed_date=p_care_date,stand_status=case when v_new_count=0 then 'failed' else 'field_care' end,metadata=metadata||jsonb_build_object('last_care_action',p_action,'last_care_date',p_care_date),updated_at=now() where id=v_stand.id returning * into v_stand;
    insert into atlas.production_field_observations(farm_id,production_lot_id,field_stand_id,task_id,object_id,crop_cycle_id,observation_type,outcome,observed_date,quantity,unit,note,idempotency_key,metadata)
    values(v_lot.farm_id,v_lot.id,v_stand.id,p_task_id,v_state.object_id,v_state.crop_cycle_id,p_action,case p_action when 'water' then 'watered' when 'weed' then 'weeded' when 'pinch' then 'pinched' when 'support' then 'supported' else 'fertility_applied' end,p_care_date,v_new_count,'plants_alive',p_note,left(v_key||':object:'||v_state.object_id::text,160),jsonb_build_object('prior_plants_alive',v_state.plants_alive,'care_policy_id',v_policy.id)) returning id into v_observation_id;
    update atlas.production_field_care_state set plants_alive=v_new_count,establishment_status=case when v_new_count=0 then 'failed' else establishment_status end,water_status=case when p_action='water' then 'adequate' else water_status end,weed_pressure=case when p_action='weed' then 'clear' else weed_pressure end,pinch_status=case when p_action='pinch' then 'done' else pinch_status end,last_watered_at=case when p_action='water' then p_care_date else last_watered_at end,last_weeded_at=case when p_action='weed' then p_care_date else last_weeded_at end,last_pinched_at=case when p_action='pinch' then p_care_date else last_pinched_at end,metadata=metadata||jsonb_build_object('last_care_task_id',p_task_id,'last_care_action',p_action,'last_observation_id',v_observation_id),updated_at=now() where id=v_state.id;
    update atlas.crop_cycles set cycle_state=case when v_new_count=0 then 'failed' else 'growing' end,lifecycle_status=case when v_new_count=0 then 'archived' else 'active' end,coverage_kind='living_plants',coverage_amount=v_new_count,coverage_unit='plants',metadata=metadata||jsonb_build_object('last_production_care_action',p_action,'last_production_care_date',p_care_date),updated_at=now() where id=v_state.crop_cycle_id;
    v_event_type:=case p_action when 'water' then 'watered' when 'weed' then 'weeded' else 'maintained' end;
    insert into atlas.object_activity_events(farm_id,object_id,field_log_id,crop_cycle_id,event_type,event_date,note,quantity,unit,created_by,source,idempotency_key,metadata)
    values(v_lot.farm_id,v_state.object_id,v_field_log,v_state.crop_cycle_id,v_event_type,p_care_date,p_note,v_new_count,'plants_alive','production_stage_engine','production_stage_engine',left(v_key||':event:'||v_state.object_id::text,160),jsonb_build_object('production_lot_id',v_lot.id,'field_stand_id',v_stand.id,'care_action',p_action,'care_policy_id',v_policy.id)) on conflict do nothing;
    insert into atlas.field_log_objects(field_log_id,zone_id,object_id,role) values(v_field_log,v_object.zone_id,v_object.id,'production_care') on conflict do nothing;
    update atlas.object_state set water_status=case when p_action='water' then 'okay' else water_status end,weed_pressure=case when p_action='weed' then 'low' else weed_pressure end,last_touched_at=p_care_date,last_watered_at=case when p_action='water' then p_care_date else last_watered_at end,last_weeded_at=case when p_action='weed' then p_care_date else last_weeded_at end,metadata=metadata||jsonb_build_object('production_lot_id',v_lot.id,'field_stand_id',v_stand.id,'living_plants',v_new_count,'last_production_care_action',p_action),updated_at=now() where object_id=v_state.object_id;
  end loop;
  select min(d) into v_next_due from (select case when v_policy.frequency_days is null then null else p_care_date+v_policy.frequency_days end d union all select case when v_policy.freshness_days is null then null else p_care_date+v_policy.freshness_days end) q where d is not null;
  update atlas.production_care_policies set current_status='satisfied',last_observation_id=v_observation_id,last_satisfied_at=p_care_date,next_due_date=v_next_due,metadata=metadata||jsonb_build_object('last_care_task_id',p_task_id,'last_care_action',p_action),updated_at=now() where id=v_policy.id;
  select coalesce(sum(current_plants),0) into v_total from atlas.production_field_stands where production_lot_id=v_lot.id and stand_status<>'cleared';
  update atlas.production_lots set current_quantity=v_total,current_unit='plants',current_stage=case when v_total=0 then 'field_failure_decision' else 'field_care' end,lifecycle_status=case when v_total=0 then 'failed' else 'active' end,metadata=metadata||jsonb_build_object('last_biological_event',p_action||'_care_completed','last_care_date',p_care_date),updated_at=now() where id=v_lot.id;
  insert into atlas.production_lot_events(farm_id,production_lot_id,event_type,event_date,quantity,unit,task_id,note,source,idempotency_key,metadata)
  values(v_lot.farm_id,v_lot.id,p_action||'_care_completed',p_care_date,v_total,'plants_alive',p_task_id,p_note,'production_stage_engine',left(v_key||':event:lot',160),jsonb_build_object('field_log_id',v_field_log,'care_policy_id',v_policy.id,'results',p_results));
  v_transition:=atlas.record_task_transition_v1_internal(p_task_id,'done',left(v_key||':task:done',160),null,coalesce(nullif(btrim(p_note),''),initcap(p_action)||' care completed.'),null,p_action,'production_lot',jsonb_build_object('production_lot_id',v_lot.id,'plants_alive',v_total,'care_policy_id',v_policy.id,'results',p_results),v_field_log);
  v_gate:=atlas.refresh_production_harvest_gate_v1(v_lot.id);
  return jsonb_build_object('taskId',p_task_id,'productionLotId',v_lot.id,'action',p_action,'plantsAlive',v_total,'nextDueDate',v_next_due,'fieldLogId',v_field_log,'harvestGate',v_gate,'deduplicated',false);
end;$$;

create or replace function atlas.record_production_harvest_readiness_v1(p_task_id uuid,p_action text,p_observations jsonb,p_observed_date date,p_recheck_date date,p_note text,p_idempotency_key text)
returns jsonb language plpgsql security definer set search_path=pg_catalog,atlas as $$
declare
  v_today date:=(now() at time zone 'America/Chicago')::date;v_task atlas.tasks%rowtype;v_lot atlas.production_lots%rowtype;v_gate atlas.production_harvest_gates%rowtype;
  v_key text:=nullif(btrim(p_idempotency_key),'');v_existing uuid;v_row record;v_stand atlas.production_field_stands%rowtype;v_transition jsonb;
  v_estimate numeric:=0;v_harvest_task uuid;v_observation_id uuid;v_not_ready integer:=0;
begin
  if p_task_id is null or p_action not in ('not_ready','ready') or p_observations is null or jsonb_typeof(p_observations)<>'array' or jsonb_array_length(p_observations)=0 or p_observed_date is null then raise exception 'Task, readiness action, per-bed observations, and date are required' using errcode='22023';end if;
  if p_action='not_ready' and (p_recheck_date is null or p_recheck_date<=p_observed_date) then raise exception 'Not-ready observation requires a later recheck date' using errcode='22023';end if;
  if v_key is null or length(v_key)>120 then raise exception 'A valid harvest-readiness idempotency key is required' using errcode='22023';end if;
  if p_observed_date>v_today+1 then raise exception 'Readiness date cannot be in the future' using errcode='22023';end if;
  select * into v_task from atlas.tasks where id=p_task_id for update;
  select pl.* into v_lot from atlas.production_lot_tasks plt join atlas.production_lots pl on pl.id=plt.production_lot_id where plt.task_id=p_task_id and plt.link_role='harvest_readiness' limit 1 for update of pl;
  if v_task.id is null or v_lot.id is null then raise exception 'Task is not a linked harvest-readiness check' using errcode='22023';end if;
  select * into v_gate from atlas.production_harvest_gates where id=v_task.generated_from_id and production_lot_id=v_lot.id for update;
  if v_gate.id is null or v_gate.harvest_readiness_task_id is distinct from p_task_id or v_gate.gate_status<>'harvest_watch' then raise exception 'Harvest gate is not open for readiness observation' using errcode='22023';end if;
  select id into v_existing from atlas.production_lot_events where farm_id=v_lot.farm_id and idempotency_key=left(v_key||':event:readiness',160);
  if v_existing is not null then return jsonb_build_object('taskId',p_task_id,'productionLotId',v_lot.id,'action',p_action,'deduplicated',true);end if;
  if v_task.status not in ('open','blocked') then raise exception 'Harvest-readiness task is not open' using errcode='22023';end if;
  create temporary table if not exists pg_temp.production_harvest_readiness_input(object_id uuid primary key,is_ready boolean not null,marketable_stem_estimate numeric) on commit drop;
  truncate pg_temp.production_harvest_readiness_input;
  insert into pg_temp.production_harvest_readiness_input(object_id,is_ready,marketable_stem_estimate)
  select (x->>'objectId')::uuid,(x->>'ready')::boolean,case when nullif(x->>'marketableStemEstimate','') is null then null else (x->>'marketableStemEstimate')::numeric end from jsonb_array_elements(p_observations) x;
  if (select count(*) from pg_temp.production_harvest_readiness_input)<>(select count(*) from atlas.production_field_stands where production_lot_id=v_lot.id and current_plants>0 and stand_status not in ('failed','cleared')) then raise exception 'Every living field stand requires a readiness observation' using errcode='22023';end if;
  if exists(select 1 from pg_temp.production_harvest_readiness_input i left join atlas.production_field_stands s on s.production_lot_id=v_lot.id and s.object_id=i.object_id and s.current_plants>0 where s.id is null or coalesce(i.marketable_stem_estimate,0)<0) then raise exception 'Readiness observations must use living field stands and nonnegative estimates' using errcode='22023';end if;
  select count(*) filter(where not is_ready),coalesce(sum(marketable_stem_estimate),0) into v_not_ready,v_estimate from pg_temp.production_harvest_readiness_input;
  if p_action='ready' and v_not_ready>0 then raise exception 'A ready cohort requires every living field stand to be marked ready' using errcode='22023';end if;
  if p_action='not_ready' and v_not_ready=0 then raise exception 'Not-ready action requires at least one stand marked not ready' using errcode='22023';end if;
  for v_row in select * from pg_temp.production_harvest_readiness_input loop
    select * into v_stand from atlas.production_field_stands where production_lot_id=v_lot.id and object_id=v_row.object_id for update;
    insert into atlas.production_field_observations(farm_id,production_lot_id,field_stand_id,task_id,object_id,crop_cycle_id,observation_type,outcome,observed_date,quantity,unit,note,idempotency_key,metadata)
    values(v_lot.farm_id,v_lot.id,v_stand.id,p_task_id,v_stand.object_id,v_stand.crop_cycle_id,'harvest_readiness',case when v_row.is_ready then 'ready' else 'not_ready' end,p_observed_date,v_row.marketable_stem_estimate,'estimated_marketable_stems',p_note,left(v_key||':stand:'||v_stand.id::text,160),jsonb_build_object('next_check_date',case when p_action='not_ready' then p_recheck_date else null end,'confidence',case when v_row.marketable_stem_estimate is null then 'observed' else 'estimated' end)) returning id into v_observation_id;
  end loop;
  insert into atlas.production_lot_events(farm_id,production_lot_id,event_type,event_date,quantity,unit,task_id,note,source,idempotency_key,metadata)
  values(v_lot.farm_id,v_lot.id,case when p_action='ready' then 'harvest_readiness_confirmed' else 'harvest_not_ready' end,p_observed_date,v_estimate,'estimated_marketable_stems',p_task_id,p_note,'production_stage_engine',left(v_key||':event:readiness',160),jsonb_build_object('harvest_gate_id',v_gate.id,'observations',p_observations,'next_check_date',p_recheck_date));
  if p_action='not_ready' then
    v_transition:=atlas.record_task_transition_v1_internal(p_task_id,'rescheduled',left(v_key||':task:not-ready',160),p_recheck_date,coalesce(nullif(btrim(p_note),''),'The field cohort is not ready to cut.'),'Harvest stage not reached.','harvest','production_lot',jsonb_build_object('production_lot_id',v_lot.id,'harvest_gate_id',v_gate.id,'estimated_marketable_stems',v_estimate,'next_check_date',p_recheck_date),null);
    return jsonb_build_object('taskId',p_task_id,'productionLotId',v_lot.id,'action','not_ready','estimatedMarketableStems',v_estimate,'nextDate',p_recheck_date,'deduplicated',false);
  end if;
  v_transition:=atlas.record_task_transition_v1_internal(p_task_id,'done',left(v_key||':task:ready',160),null,coalesce(nullif(btrim(p_note),''),'Every living field stand reached harvest readiness.'),null,'harvest','production_lot',jsonb_build_object('production_lot_id',v_lot.id,'harvest_gate_id',v_gate.id,'estimated_marketable_stems',v_estimate),null);
  insert into atlas.tasks(farm_id,title,task_type,status,priority,due_date,generated_from,generated_from_id,note,metadata,action_key,work_class,task_series_key,engine_instance_key,visibility_scope,assigned_membership_id)
  values(v_lot.farm_id,'Harvest + count marketable stems — '||v_lot.lot_label,'production_harvest','open','high',p_observed_date,'production_harvest_gate',v_gate.id,'Cut this exact cohort and record actual marketable, second-quality, and discarded stems. The readiness estimate is not the harvest count.',jsonb_build_object('task_key','production_harvest_'||v_gate.id::text,'task_style','production_harvest','production_lot_id',v_lot.id,'production_lot_key',v_lot.stable_key,'production_harvest_gate_id',v_gate.id,'readiness_estimated_marketable_stems',v_estimate,'display_action','Harvest + count','display_subject',v_lot.lot_label,'display_detail',case when v_estimate>0 then v_estimate::text||' estimated marketable stems' else 'Count actual cut stems' end,'collection_zone','Production beds'),'harvest','standard','production-lot:'||v_lot.stable_key||':harvest','production-harvest:'||v_gate.id::text,v_task.visibility_scope,v_task.assigned_membership_id) returning id into v_harvest_task;
  update atlas.production_harvest_gates set gate_status='harvest_ready',harvest_task_id=v_harvest_task,ready_at=now(),blocker_text=null,metadata=metadata||jsonb_build_object('readiness_date',p_observed_date,'readiness_estimated_marketable_stems',v_estimate),updated_at=now() where id=v_gate.id;
  update atlas.production_lots set current_stage='harvest_watch',metadata=metadata||jsonb_build_object('last_biological_event','harvest_readiness_confirmed','harvest_readiness_date',p_observed_date,'readiness_estimated_marketable_stems',v_estimate),updated_at=now() where id=v_lot.id;
  update atlas.production_field_stands set stand_status='harvest_watch',metadata=metadata||jsonb_build_object('harvest_readiness_date',p_observed_date),updated_at=now() where production_lot_id=v_lot.id and current_plants>0;
  update atlas.crop_cycles set cycle_state='harvest_watch',expected_harvest_watch_start=coalesce(expected_harvest_watch_start,p_observed_date),metadata=metadata||jsonb_build_object('harvest_readiness_date',p_observed_date),updated_at=now() where id in (select crop_cycle_id from atlas.production_field_stands where production_lot_id=v_lot.id and current_plants>0);
  insert into atlas.production_lot_tasks(production_lot_id,task_id,link_role,source,metadata) values(v_lot.id,v_harvest_task,'harvest','production_stage_engine',jsonb_build_object('harvest_gate_id',v_gate.id,'readiness_task_id',p_task_id,'estimated_marketable_stems',v_estimate));
  insert into atlas.task_objects(task_id,object_id,role) select v_harvest_task,object_id,'harvest_source' from atlas.production_field_stands where production_lot_id=v_lot.id and current_plants>0 on conflict do nothing;
  insert into atlas.task_crop_cycles(task_id,crop_cycle_id,role,confidence,source,metadata) select v_harvest_task,crop_cycle_id,'harvests','confirmed','production_stage_engine',jsonb_build_object('harvest_gate_id',v_gate.id) from atlas.production_field_stands where production_lot_id=v_lot.id and current_plants>0 on conflict do nothing;
  return jsonb_build_object('taskId',p_task_id,'productionLotId',v_lot.id,'action','ready','estimatedMarketableStems',v_estimate,'harvestTaskId',v_harvest_task,'deduplicated',false);
end;$$;