grant select on table
  atlas.farms,
  atlas.zones,
  atlas.growing_objects,
  atlas.crop_profiles,
  atlas.field_logs,
  atlas.field_log_objects,
  atlas.planting_claims,
  atlas.planting_claim_objects,
  atlas.object_contents,
  atlas.object_state,
  atlas.tasks,
  atlas.task_objects,
  atlas.projects,
  atlas.project_steps,
  atlas.resources,
  atlas.action_requirement_templates,
  atlas.task_resource_requirements,
  atlas.project_goals,
  atlas.task_outcome_events,
  atlas.crop_cycles,
  atlas.plant_lineages,
  atlas.plant_instances,
  atlas.propagation_events,
  atlas.maintenance_objects,
  atlas.maintenance_scheduler_settings,
  atlas.maintenance_dependencies,
  atlas.maintenance_history,
  atlas.maintenance_type_profiles,
  atlas.truth_sources,
  atlas.truth_assertions,
  atlas.integrity_audit_runs,
  atlas.identity_review_queue,
  atlas.object_content_resolutions,
  atlas.object_content_entity_links,
  atlas.task_transitions,
  atlas.production_plans,
  atlas.production_successions,
  atlas.production_rule_templates,
  atlas.user_profiles,
  atlas.farm_memberships
  to authenticated;

grant select on atlas.v_farm_object_operational_state to authenticated, service_role;