update atlas.crop_profiles cp
set metadata=jsonb_set(coalesce(cp.metadata,'{}'::jsonb),'{use_tags}',coalesce(cp.metadata->'use_tags','[]'::jsonb)||to_jsonb('cut_flower'::text),true),updated_at=now()
where cp.stable_key in ('celosia_cut_flower','pollenless_sunflower_generic','sunflower_gift_seed_mix','sunflower_gold_lite','sunflower_procut_plum','sunflower_starburst_panache','zinnia_cut_flower_generic')
and not (coalesce(cp.metadata->'use_tags','[]'::jsonb) ? 'cut_flower');

update atlas.crop_profiles cp
set metadata=jsonb_set(coalesce(cp.metadata,'{}'::jsonb),'{use_tags}',coalesce(cp.metadata->'use_tags','[]'::jsonb)||to_jsonb('food'::text),true),updated_at=now()
where cp.stable_key in ('crookneck_squash_generic','ground_cherry_generic','mini_spaghetti_squash','pumpkin_pie_squash','fall_kale_seedling','fall_lettuce_seedling','fall_onion_seedling')
and not (coalesce(cp.metadata->'use_tags','[]'::jsonb) ? 'food');

alter table atlas.weekly_harvest_task_results drop constraint if exists weekly_harvest_task_results_result_kind_check;
alter table atlas.weekly_harvest_task_results add constraint weekly_harvest_task_results_result_kind_check check (result_kind=any(array['harvest_amount'::text,'food_picked'::text,'not_ready'::text,'deadheaded'::text,'crop_exhausted'::text]));
alter table atlas.weekly_harvest_task_results drop constraint if exists weekly_harvest_task_results_v2_shape_check;
alter table atlas.weekly_harvest_task_results add constraint weekly_harvest_task_results_v2_shape_check check ((result_kind='harvest_amount' and bucket_halves is not null and bucket_halves>=1 and bucket_band is null and more_availability is null) or (result_kind=any(array['food_picked'::text,'not_ready'::text,'deadheaded'::text,'crop_exhausted'::text]) and bucket_halves is null and bucket_band is null and more_availability is null));

create or replace function atlas.weekly_harvest_candidate_cycles_v1(p_task_id uuid)
returns table(crop_cycle_id uuid,crop_label text,variety text,object_id uuid,object_label text,window_start date,window_end date,cycle_state text,availability_status text)
language sql stable security definer set search_path to 'pg_catalog','atlas' as $function$
with ctx as (select t.id,t.farm_id,coalesce(t.due_date,(now() at time zone 'America/Chicago')::date) service_date from atlas.tasks t where t.id=p_task_id and t.task_type='harvest' and t.task_series_key='anna_harvest_thursday_weekly')
select cc.id,coalesce(nullif(cc.crop_label,''),'Crop'),nullif(cc.variety,''),go.id,coalesce(nullif(go.label,''),'Growing area'),cc.expected_harvest_watch_start,coalesce(cc.expected_harvest_watch_end,cc.expected_harvest_watch_start+21),coalesce(nullif(cc.cycle_state,''),'growing'),cha.status
from ctx join atlas.crop_cycles cc on cc.farm_id=ctx.farm_id join atlas.crop_profiles cp on cp.id=cc.crop_profile_id join atlas.growing_objects go on go.id=cc.object_id left join atlas.crop_harvest_availability cha on cha.crop_cycle_id=cc.id
where coalesce(cc.lifecycle_status,'active')='active' and coalesce(cp.metadata->'use_tags','[]'::jsonb)?'cut_flower' and cc.expected_harvest_watch_start is not null and coalesce(go.stable_key,'') not like 'grow_room_%' and lower(coalesce(cc.cycle_state,'')) not in ('failed','cleared','finished','finished_harvest') and coalesce(cha.status,'watching')<>'finished' and ((cc.expected_harvest_watch_start<=ctx.service_date and coalesce(cc.expected_harvest_watch_end,cc.expected_harvest_watch_start+21)>=ctx.service_date) or cc.harvest_started_date is not null or exists(select 1 from atlas.crop_harvest_events e where e.crop_cycle_id=cc.id and e.event_kind='cut' and e.observed_date>=ctx.service_date-14))
order by go.label,cc.crop_label,cc.variety,cc.id;
$function$;

create or replace function atlas.weekly_harvest_task_state_core_v1(p_task_id uuid,p_effective_membership_id uuid,p_effective_role text,p_operator_mode boolean default false)
returns jsonb language plpgsql security definer set search_path to 'pg_catalog','atlas' as $function$
declare v_task atlas.tasks%rowtype; v_member atlas.farm_memberships%rowtype; v_rows jsonb:='[]'::jsonb; v_total integer:=0; v_resolved integer:=0;
begin
select * into v_task from atlas.tasks where id=p_task_id; if v_task.id is null then raise exception 'Weekly Harvest task not found.' using errcode='P0002'; end if; if v_task.task_type<>'harvest' or v_task.task_series_key<>'anna_harvest_thursday_weekly' then raise exception 'Task is not the canonical weekly Harvest card.' using errcode='22023'; end if;
select * into v_member from atlas.farm_memberships where id=p_effective_membership_id; if v_member.id is null or not v_member.active or v_member.farm_id is distinct from v_task.farm_id then raise exception 'Active farm membership required.' using errcode='42501'; end if; if p_effective_role not in ('owner','manager','farm_hand') then raise exception 'Harvest access denied.' using errcode='42501'; end if; if p_effective_role='farm_hand' and v_task.assigned_membership_id is distinct from p_effective_membership_id then raise exception 'Weekly Harvest is not assigned to this worker.' using errcode='42501'; end if;
with current_candidates as (select c.*,coalesce(nullif(z.label,''),'Elm Farm') zone_label from atlas.weekly_harvest_candidate_cycles_v1(v_task.id)c join atlas.growing_objects go on go.id=c.object_id left join atlas.zones z on z.id=go.zone_id), historical_results as (select cc.id crop_cycle_id,coalesce(nullif(cc.crop_label,''),'Crop') crop_label,nullif(cc.variety,'') variety,go.id object_id,coalesce(nullif(go.label,''),'Growing area') object_label,cc.expected_harvest_watch_start window_start,coalesce(cc.expected_harvest_watch_end,cc.expected_harvest_watch_start+21) window_end,coalesce(nullif(cc.cycle_state,''),'growing') cycle_state,cha.status availability_status,coalesce(nullif(z.label,''),'Elm Farm') zone_label from atlas.weekly_harvest_task_results wr join atlas.crop_cycles cc on cc.id=wr.crop_cycle_id join atlas.growing_objects go on go.id=cc.object_id left join atlas.zones z on z.id=go.zone_id left join atlas.crop_harvest_availability cha on cha.crop_cycle_id=cc.id where wr.task_id=v_task.id and wr.result_kind<>'crop_exhausted'), rows_union as (select * from current_candidates union select * from historical_results)
select coalesce(jsonb_agg(jsonb_strip_nulls(jsonb_build_object('cropCycleId',u.crop_cycle_id,'cropLabel',u.crop_label,'variety',u.variety,'zoneLabel',u.zone_label,'objectId',u.object_id,'objectLabel',u.object_label,'windowStart',u.window_start,'windowEnd',u.window_end,'cycleState',u.cycle_state,'availabilityStatus',u.availability_status,'resolved',wr.id is not null,'resultKind',wr.result_kind,'bucketHalves',wr.bucket_halves,'resolvedAt',wr.resolved_at)) order by u.zone_label,u.object_label,u.crop_label,u.variety,u.crop_cycle_id),'[]'::jsonb),count(*)::integer,count(wr.id)::integer into v_rows,v_total,v_resolved from rows_union u left join atlas.weekly_harvest_task_results wr on wr.task_id=v_task.id and wr.crop_cycle_id=u.crop_cycle_id;
return jsonb_build_object('contractVersion','weekly_harvest_round_v2','taskId',v_task.id,'status',v_task.status,'dueDate',v_task.due_date,'rows',v_rows,'totalRows',v_total,'resolvedRows',v_resolved,'complete',v_total>0 and v_total=v_resolved,'operatorMode',p_operator_mode,'truthBoundary',jsonb_build_object('oneWorkerFacingHarvestCard',true,'cropRowsAreNotTasks',true,'cropCycleTruthRemainsCanonical',true,'cutFlowerUseTagRequired',true,'cropExhaustedLeavesCard',true,'positiveBucketCountIsHarvestResult',true,'onlySelectableExceptions',jsonb_build_array('not_ready','deadheaded','crop_exhausted'),'bucketIncrement',0.5));
end;$function$;

create or replace function atlas.weekly_food_harvest_candidate_cycles_v1(p_task_id uuid)
returns table(crop_cycle_id uuid,crop_label text,variety text,object_id uuid,object_label text,window_start date,window_end date,cycle_state text,availability_status text)
language sql stable security definer set search_path to 'pg_catalog','atlas' as $function$
with ctx as (select t.id,t.farm_id,coalesce(t.due_date,(now() at time zone 'America/Chicago')::date) service_date from atlas.tasks t where t.id=p_task_id and t.task_type='food_harvest' and t.task_series_key='anna_food_harvest_tuesday_weekly')
select cc.id,coalesce(nullif(cc.crop_label,''),'Crop'),nullif(cc.variety,''),go.id,coalesce(nullif(go.label,''),'Growing area'),cc.expected_harvest_watch_start,coalesce(cc.expected_harvest_watch_end,cc.expected_harvest_watch_start+21),coalesce(nullif(cc.cycle_state,''),'growing'),cha.status
from ctx join atlas.crop_cycles cc on cc.farm_id=ctx.farm_id join atlas.crop_profiles cp on cp.id=cc.crop_profile_id join atlas.growing_objects go on go.id=cc.object_id left join atlas.crop_harvest_availability cha on cha.crop_cycle_id=cc.id
where coalesce(cc.lifecycle_status,'active')='active' and coalesce(cp.metadata->'use_tags','[]'::jsonb)?'food' and cc.expected_harvest_watch_start is not null and coalesce(go.stable_key,'') not like 'grow_room_%' and lower(coalesce(cc.cycle_state,'')) not in ('failed','cleared','finished','finished_harvest') and coalesce(cha.status,'watching')<>'finished' and cc.expected_harvest_watch_start<=ctx.service_date and coalesce(cc.expected_harvest_watch_end,cc.expected_harvest_watch_start+21)>=ctx.service_date
order by go.label,cc.crop_label,cc.variety,cc.id;
$function$;

create or replace function atlas.ensure_weekly_food_harvest_card_v1(p_farm_id uuid,p_due_date date)
returns jsonb language plpgsql security definer set search_path to 'pg_catalog','atlas' as $function$
declare v_member atlas.farm_memberships%rowtype; v_existing atlas.tasks%rowtype; v_occurrence uuid; v_materialized jsonb; v_task_id uuid; v_has_candidates boolean:=false;
begin
if p_farm_id is null or p_due_date is null then raise exception 'Farm and Food Harvest service date are required.' using errcode='22023'; end if; if extract(isodow from p_due_date)::integer<>2 then raise exception 'Weekly Food Harvest is a Tuesday card.' using errcode='22023'; end if;
select * into v_member from atlas.farm_memberships where farm_id=p_farm_id and active and worker_key='anna' order by created_at limit 1; if v_member.id is null then return jsonb_build_object('state','anna_membership_missing','dueDate',p_due_date); end if;
select exists(select 1 from atlas.crop_cycles cc join atlas.crop_profiles cp on cp.id=cc.crop_profile_id where cc.farm_id=p_farm_id and coalesce(cc.lifecycle_status,'active')='active' and coalesce(cp.metadata->'use_tags','[]'::jsonb)?'food' and cc.expected_harvest_watch_start is not null and lower(coalesce(cc.cycle_state,'')) not in ('failed','cleared','finished','finished_harvest') and cc.expected_harvest_watch_start<=p_due_date and coalesce(cc.expected_harvest_watch_end,cc.expected_harvest_watch_start+21)>=p_due_date) into v_has_candidates; if not v_has_candidates then return jsonb_build_object('state','no_food_in_window','dueDate',p_due_date); end if;
select * into v_existing from atlas.tasks where farm_id=p_farm_id and task_series_key='anna_food_harvest_tuesday_weekly' and due_date=p_due_date and status<>'archived' order by created_at limit 1; if v_existing.id is not null then return jsonb_build_object('state','kept_current','taskId',v_existing.id,'occurrenceId',v_existing.planned_occurrence_id,'dueDate',p_due_date); end if;
v_occurrence:=atlas.plan_fixed_assigned_worker_occurrence_v1(p_farm_id=>p_farm_id,p_membership_id=>v_member.id,p_user_id=>v_member.user_id,p_definition_key=>'anna_food_harvest_tuesday_weekly_2026',p_policy_key=>'anna_food_harvest_tuesday_weekly_2026:release',p_occurrence_key=>'recurring:anna_food_harvest_tuesday_weekly:'||p_due_date::text,p_title=>'Harvest Food',p_task_type=>'food_harvest',p_due_date=>p_due_date,p_priority=>'normal',p_action_key=>'harvest',p_series_key=>'anna_food_harvest_tuesday_weekly',p_effort_units=>0.5,p_metadata=>jsonb_build_object('task_style','weekly_food_harvest_round','weekly_routine',true,'repeat_rule','weekly','repeat_weekday','Tuesday','display_action','Harvest food','display_subject','Garden food','display_location','Elm Farm','collection_zone','Elm Farm','collection_label','Food Harvest','work_route','harvest','work_order_anchor','morning','structured_result_required',true,'result_contract','weekly_food_harvest_round_v1','crop_rows_derived_from_domain_truth',true,'food_output_not_flower_inventory',true));
if p_due_date<=(now() at time zone 'America/Chicago')::date then v_materialized:=atlas.materialize_specific_work_occurrence_v1(v_occurrence,(now() at time zone 'America/Chicago')::date); begin v_task_id:=nullif(v_materialized->>'taskId','')::uuid; exception when others then v_task_id:=null; end; end if;
return jsonb_build_object('state',case when v_task_id is null then 'planned' else 'released' end,'taskId',v_task_id,'occurrenceId',v_occurrence,'dueDate',p_due_date); end;$function$;

create or replace function atlas.weekly_food_harvest_task_state_core_v1(p_task_id uuid,p_effective_membership_id uuid,p_effective_role text,p_operator_mode boolean default false)
returns jsonb language plpgsql security definer set search_path to 'pg_catalog','atlas' as $function$
declare v_task atlas.tasks%rowtype; v_member atlas.farm_memberships%rowtype; v_rows jsonb:='[]'::jsonb; v_total integer:=0; v_resolved integer:=0;
begin
select * into v_task from atlas.tasks where id=p_task_id; if v_task.id is null then raise exception 'Food Harvest task not found.' using errcode='P0002'; end if; if v_task.task_type<>'food_harvest' or v_task.task_series_key<>'anna_food_harvest_tuesday_weekly' then raise exception 'Task is not the canonical weekly Food Harvest card.' using errcode='22023'; end if;
select * into v_member from atlas.farm_memberships where id=p_effective_membership_id; if v_member.id is null or not v_member.active or v_member.farm_id is distinct from v_task.farm_id then raise exception 'Active farm membership required.' using errcode='42501'; end if; if p_effective_role not in ('owner','manager','farm_hand') then raise exception 'Food Harvest access denied.' using errcode='42501'; end if; if p_effective_role='farm_hand' and v_task.assigned_membership_id is distinct from p_effective_membership_id then raise exception 'Food Harvest is not assigned to this worker.' using errcode='42501'; end if;
with current_candidates as (select c.*,coalesce(nullif(z.label,''),'Elm Farm') zone_label from atlas.weekly_food_harvest_candidate_cycles_v1(v_task.id)c join atlas.growing_objects go on go.id=c.object_id left join atlas.zones z on z.id=go.zone_id), historical_results as (select cc.id crop_cycle_id,coalesce(nullif(cc.crop_label,''),'Crop') crop_label,nullif(cc.variety,'') variety,go.id object_id,coalesce(nullif(go.label,''),'Growing area') object_label,cc.expected_harvest_watch_start window_start,coalesce(cc.expected_harvest_watch_end,cc.expected_harvest_watch_start+21) window_end,coalesce(nullif(cc.cycle_state,''),'growing') cycle_state,cha.status availability_status,coalesce(nullif(z.label,''),'Elm Farm') zone_label from atlas.weekly_harvest_task_results wr join atlas.crop_cycles cc on cc.id=wr.crop_cycle_id join atlas.growing_objects go on go.id=cc.object_id left join atlas.zones z on z.id=go.zone_id left join atlas.crop_harvest_availability cha on cha.crop_cycle_id=cc.id where wr.task_id=v_task.id and wr.result_kind<>'crop_exhausted'), rows_union as (select * from current_candidates union select * from historical_results)
select coalesce(jsonb_agg(jsonb_strip_nulls(jsonb_build_object('cropCycleId',u.crop_cycle_id,'cropLabel',u.crop_label,'variety',u.variety,'zoneLabel',u.zone_label,'objectId',u.object_id,'objectLabel',u.object_label,'windowStart',u.window_start,'windowEnd',u.window_end,'cycleState',u.cycle_state,'availabilityStatus',u.availability_status,'resolved',wr.id is not null,'resultKind',wr.result_kind,'resolvedAt',wr.resolved_at)) order by u.zone_label,u.object_label,u.crop_label,u.variety,u.crop_cycle_id),'[]'::jsonb),count(*)::integer,count(wr.id)::integer into v_rows,v_total,v_resolved from rows_union u left join atlas.weekly_harvest_task_results wr on wr.task_id=v_task.id and wr.crop_cycle_id=u.crop_cycle_id;
return jsonb_build_object('contractVersion','weekly_food_harvest_round_v1','taskId',v_task.id,'status',v_task.status,'dueDate',v_task.due_date,'rows',v_rows,'totalRows',v_total,'resolvedRows',v_resolved,'complete',v_total>0 and v_total=v_resolved,'operatorMode',p_operator_mode,'truthBoundary',jsonb_build_object('foodUseTagRequired',true,'doesNotCreateFlowerInventory',true,'cropExhaustedLeavesCard',true)); end;$function$;

create or replace function atlas.weekly_food_harvest_task_state_for_member_v1(p_farm_id uuid,p_task_id uuid) returns jsonb language plpgsql security definer set search_path to 'pg_catalog','atlas','auth' as $function$ declare v_role text; v_membership uuid; begin v_role:=atlas.current_farm_role(p_farm_id); v_membership:=atlas.current_membership_id(p_farm_id); if auth.uid() is null or v_role is null or v_membership is null then raise exception 'Active farm membership required.' using errcode='42501'; end if; return atlas.weekly_food_harvest_task_state_core_v1(p_task_id,v_membership,v_role,false); end;$function$;
create or replace function atlas.owner_operator_weekly_food_harvest_task_state_v1(p_effective_membership_id uuid,p_task_id uuid) returns jsonb language plpgsql security definer set search_path to 'pg_catalog','atlas','auth' as $function$ declare v_context jsonb; begin v_context:=atlas.owner_operator_context_v1(p_effective_membership_id); return atlas.weekly_food_harvest_task_state_core_v1(p_task_id,(v_context#>>'{effective,membershipId}')::uuid,v_context#>>'{effective,role}',true); end;$function$;

create or replace function atlas.record_weekly_food_harvest_row_core_v1(p_task_id uuid,p_crop_cycle_id uuid,p_effective_membership_id uuid,p_effective_role text,p_result_kind text,p_idempotency_key text,p_operator_mode boolean default false)
returns jsonb language plpgsql security definer set search_path to 'pg_catalog','atlas','auth' as $function$
declare v_task atlas.tasks%rowtype; v_cycle atlas.crop_cycles%rowtype; v_member atlas.farm_memberships%rowtype; v_existing atlas.weekly_harvest_task_results%rowtype; v_kind text:=lower(btrim(coalesce(p_result_kind,''))); v_today date:=(now() at time zone 'America/Chicago')::date; v_next_tuesday date; v_event atlas.crop_harvest_events%rowtype; v_result atlas.weekly_harvest_task_results%rowtype; v_unresolved integer:=0; v_transition jsonb; v_next jsonb;
begin
if v_kind not in ('food_picked','not_ready','crop_exhausted') then raise exception 'Choose Picked, Not ready, or Crop exhausted.' using errcode='22023'; end if; if nullif(btrim(coalesce(p_idempotency_key,'')),'') is null then raise exception 'Food Harvest idempotency key is required.' using errcode='22023'; end if;
select * into v_task from atlas.tasks where id=p_task_id for update; if v_task.id is null then raise exception 'Food Harvest task not found.' using errcode='P0002'; end if; if v_task.status not in ('open','blocked') or v_task.task_type<>'food_harvest' or v_task.task_series_key<>'anna_food_harvest_tuesday_weekly' then raise exception 'Food Harvest card is not open.' using errcode='22023'; end if;
select * into v_member from atlas.farm_memberships where id=p_effective_membership_id; if v_member.id is null or not v_member.active or v_member.farm_id is distinct from v_task.farm_id then raise exception 'Active farm membership required.' using errcode='42501'; end if; if p_effective_role not in ('owner','manager','farm_hand') then raise exception 'Food Harvest access denied.' using errcode='42501'; end if; if p_effective_role='farm_hand' and v_task.assigned_membership_id is distinct from p_effective_membership_id then raise exception 'Food Harvest is not assigned to this worker.' using errcode='42501'; end if;
select * into v_existing from atlas.weekly_harvest_task_results where farm_id=v_task.farm_id and idempotency_key=p_idempotency_key; if v_existing.id is null then select * into v_existing from atlas.weekly_harvest_task_results where task_id=v_task.id and crop_cycle_id=p_crop_cycle_id; end if; if v_existing.id is not null then return jsonb_build_object('contractVersion','weekly_food_harvest_round_v1','deduplicated',true,'resultId',v_existing.id,'taskId',v_task.id,'cropCycleId',v_existing.crop_cycle_id,'resultKind',v_existing.result_kind); end if;
select cc.* into v_cycle from atlas.weekly_food_harvest_candidate_cycles_v1(v_task.id)c join atlas.crop_cycles cc on cc.id=c.crop_cycle_id where c.crop_cycle_id=p_crop_cycle_id; if v_cycle.id is null then raise exception 'Crop is not on this Food Harvest card.' using errcode='22023'; end if; v_next_tuesday:=v_today+case when ((2-extract(isodow from v_today)::integer+7)%7)=0 then 7 else ((2-extract(isodow from v_today)::integer+7)%7) end;
insert into atlas.crop_harvest_events(farm_id,crop_cycle_id,task_id,event_kind,outcome,observed_date,next_check_date,more_available,note,idempotency_key,created_by_user_id,metadata) values(v_task.farm_id,v_cycle.id,v_task.id,case when v_kind='food_picked' then 'pick' else 'watch' end,case when v_kind='food_picked' then 'harvested_more' when v_kind='crop_exhausted' then 'finished' else 'not_ready' end,v_today,case when v_kind='not_ready' then v_next_tuesday else null end,case when v_kind='food_picked' then true else null end,null,p_idempotency_key,auth.uid(),jsonb_build_object('weeklyFoodHarvestTaskId',v_task.id,'foodOutput',true,'flowerInventoryEffect','none','operatorMode',p_operator_mode,'rawResultKind',v_kind)) returning * into v_event;
update atlas.crop_cycles set harvest_started_date=case when v_kind='food_picked' then coalesce(harvest_started_date,v_today) else harvest_started_date end,last_harvest_date=case when v_kind='food_picked' then v_today else last_harvest_date end,cycle_state=case when v_kind='crop_exhausted' then 'finished_harvest' else 'harvest_watch' end,metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('last_food_harvest_action',v_kind,'last_food_harvest_date',v_today,'weekly_food_harvest_task_id',v_task.id),updated_at=now() where id=v_cycle.id;
insert into atlas.crop_harvest_availability(crop_cycle_id,farm_id,status,observed_date,source_event_id,current_watch_task_id,current_watch_occurrence_id,current_harvest_task_id,current_harvest_occurrence_id,metadata) values(v_cycle.id,v_task.farm_id,case when v_kind='crop_exhausted' then 'finished' else 'watching' end,v_today,v_event.id,null,null,null,null,jsonb_build_object('weeklyFoodHarvestTaskId',v_task.id,'lastAction',v_kind,'foodOutput',true)) on conflict(crop_cycle_id) do update set status=excluded.status,observed_date=excluded.observed_date,source_event_id=excluded.source_event_id,current_watch_task_id=null,current_watch_occurrence_id=null,current_harvest_task_id=null,current_harvest_occurrence_id=null,metadata=atlas.crop_harvest_availability.metadata||excluded.metadata,updated_at=now();
insert into atlas.weekly_harvest_task_results(farm_id,task_id,crop_cycle_id,result_kind,bucket_halves,bucket_band,more_availability,note,crop_harvest_event_id,flower_harvest_observation_id,resolved_by_membership_id,idempotency_key,metadata) values(v_task.farm_id,v_task.id,v_cycle.id,v_kind,null,null,null,null,v_event.id,null,p_effective_membership_id,p_idempotency_key,jsonb_build_object('operatorMode',p_operator_mode,'contractVersion','weekly_food_harvest_round_v1','flowerInventoryEffect','none')) returning * into v_result;
select count(*)::integer into v_unresolved from atlas.weekly_food_harvest_candidate_cycles_v1(v_task.id)c left join atlas.weekly_harvest_task_results r on r.task_id=v_task.id and r.crop_cycle_id=c.crop_cycle_id where r.id is null; if v_unresolved=0 and exists(select 1 from atlas.weekly_harvest_task_results where task_id=v_task.id) then v_transition:=atlas.record_task_transition_v1_internal(v_task.id,'done','weekly-food-harvest:auto:v1:'||v_task.id::text,null,'Every food crop on this Tuesday card was physically resolved.',null,'harvest','weekly_food_harvest_round',jsonb_build_object('completion_source','weekly_food_harvest_results_v1','last_result_id',v_result.id),null); v_next:=atlas.ensure_weekly_food_harvest_card_v1(v_task.farm_id,v_task.due_date+7); end if;
return jsonb_build_object('contractVersion','weekly_food_harvest_round_v1','deduplicated',false,'resultId',v_result.id,'taskId',v_task.id,'cropCycleId',v_cycle.id,'resultKind',v_kind,'remainingRows',v_unresolved,'taskCompleted',v_transition is not null,'nextWeeklyCard',v_next); end;$function$;

create or replace function atlas.record_weekly_food_harvest_row_for_member_v1(p_farm_id uuid,p_task_id uuid,p_crop_cycle_id uuid,p_result_kind text,p_idempotency_key text) returns jsonb language plpgsql security definer set search_path to 'pg_catalog','atlas','auth' as $function$ declare v_role text; v_membership uuid; begin v_role:=atlas.current_farm_role(p_farm_id); v_membership:=atlas.current_membership_id(p_farm_id); if auth.uid() is null or v_role is null or v_membership is null then raise exception 'Active farm membership required.' using errcode='42501'; end if; return atlas.record_weekly_food_harvest_row_core_v1(p_task_id,p_crop_cycle_id,v_membership,v_role,p_result_kind,p_idempotency_key,false); end;$function$;
create or replace function atlas.owner_operator_record_weekly_food_harvest_row_v1(p_effective_membership_id uuid,p_task_id uuid,p_crop_cycle_id uuid,p_result_kind text,p_idempotency_key text) returns jsonb language plpgsql security definer set search_path to 'pg_catalog','atlas','auth' as $function$ declare v_context jsonb; begin v_context:=atlas.owner_operator_context_v1(p_effective_membership_id); return atlas.record_weekly_food_harvest_row_core_v1(p_task_id,p_crop_cycle_id,(v_context#>>'{effective,membershipId}')::uuid,v_context#>>'{effective,role}',p_result_kind,p_idempotency_key,true); end;$function$;

revoke all on function atlas.weekly_food_harvest_candidate_cycles_v1(uuid) from public,anon,authenticated; revoke all on function atlas.ensure_weekly_food_harvest_card_v1(uuid,date) from public,anon,authenticated; revoke all on function atlas.weekly_food_harvest_task_state_core_v1(uuid,uuid,text,boolean) from public,anon,authenticated; revoke all on function atlas.record_weekly_food_harvest_row_core_v1(uuid,uuid,uuid,text,text,text,boolean) from public,anon,authenticated; revoke all on function atlas.weekly_food_harvest_task_state_for_member_v1(uuid,uuid) from public,anon; revoke all on function atlas.owner_operator_weekly_food_harvest_task_state_v1(uuid,uuid) from public,anon; revoke all on function atlas.record_weekly_food_harvest_row_for_member_v1(uuid,uuid,uuid,text,text) from public,anon; revoke all on function atlas.owner_operator_record_weekly_food_harvest_row_v1(uuid,uuid,uuid,text,text) from public,anon;
grant execute on function atlas.weekly_food_harvest_candidate_cycles_v1(uuid) to service_role; grant execute on function atlas.ensure_weekly_food_harvest_card_v1(uuid,date) to service_role; grant execute on function atlas.weekly_food_harvest_task_state_core_v1(uuid,uuid,text,boolean) to service_role; grant execute on function atlas.record_weekly_food_harvest_row_core_v1(uuid,uuid,uuid,text,text,text,boolean) to service_role; grant execute on function atlas.weekly_food_harvest_task_state_for_member_v1(uuid,uuid) to authenticated,service_role; grant execute on function atlas.owner_operator_weekly_food_harvest_task_state_v1(uuid,uuid) to authenticated,service_role; grant execute on function atlas.record_weekly_food_harvest_row_for_member_v1(uuid,uuid,uuid,text,text) to authenticated,service_role; grant execute on function atlas.owner_operator_record_weekly_food_harvest_row_v1(uuid,uuid,uuid,text,text) to authenticated,service_role;

insert into atlas.authenticated_rpc_registry(signature,classification,confidence,review_status,authenticated_execute_expected,security_definer_expected,service_execute_expected,caller_count,policy_reference_count,evidence,registered_at,reviewed_at,anonymous_execute_expected) values
('atlas.weekly_food_harvest_candidate_cycles_v1(uuid)','service_internal','verified','active',false,true,true,0,0,jsonb_build_object('purpose','Resolve food-tagged crop-cycle rows for Tuesday Food Harvest.','directSignedInEndpoint',false),now(),now(),false),
('atlas.ensure_weekly_food_harvest_card_v1(uuid, date)','service_internal','verified','active',false,true,true,0,0,jsonb_build_object('purpose','Materialize the Tuesday Food Harvest carrier only when food crops are in window.','directSignedInEndpoint',false),now(),now(),false),
('atlas.weekly_food_harvest_task_state_core_v1(uuid, uuid, text, boolean)','service_internal','verified','active',false,true,true,0,0,jsonb_build_object('purpose','Shared Food Harvest state reader behind authorized wrappers.','directSignedInEndpoint',false),now(),now(),false),
('atlas.record_weekly_food_harvest_row_core_v1(uuid, uuid, uuid, text, text, text, boolean)','service_internal','verified','active',false,true,true,0,0,jsonb_build_object('purpose','Shared Food Harvest writer; never creates flower inventory.','directSignedInEndpoint',false),now(),now(),false),
('atlas.weekly_food_harvest_task_state_for_member_v1(uuid, uuid)','app_endpoint','verified','active',true,true,true,1,0,jsonb_build_object('caller','GET /api/atlas/weekly-food-harvest','purpose','Read Tuesday Food Harvest for signed-in farm member.'),now(),now(),false),
('atlas.owner_operator_weekly_food_harvest_task_state_v1(uuid, uuid)','owner_admin_endpoint','verified','active',true,true,true,1,0,jsonb_build_object('caller','GET /api/atlas/weekly-food-harvest','purpose','Read Tuesday Food Harvest in Owner operator mode.'),now(),now(),false),
('atlas.record_weekly_food_harvest_row_for_member_v1(uuid, uuid, uuid, text, text)','app_endpoint','verified','active',true,true,true,1,0,jsonb_build_object('caller','POST /api/atlas/weekly-food-harvest','purpose','Record Picked, Not ready, or Crop exhausted without flower inventory.'),now(),now(),false),
('atlas.owner_operator_record_weekly_food_harvest_row_v1(uuid, uuid, uuid, text, text)','owner_admin_endpoint','verified','active',true,true,true,1,0,jsonb_build_object('caller','POST /api/atlas/weekly-food-harvest','purpose','Record Food Harvest result in Owner operator mode.'),now(),now(),false)
on conflict(signature) do update set classification=excluded.classification,confidence=excluded.confidence,review_status=excluded.review_status,authenticated_execute_expected=excluded.authenticated_execute_expected,security_definer_expected=excluded.security_definer_expected,service_execute_expected=excluded.service_execute_expected,caller_count=excluded.caller_count,policy_reference_count=excluded.policy_reference_count,evidence=excluded.evidence,reviewed_at=now(),anonymous_execute_expected=excluded.anonymous_execute_expected;

select atlas.ensure_weekly_food_harvest_card_v1(f.id,date '2026-08-25') from atlas.farms f where f.stable_key='elm_farm';