create or replace function atlas.record_production_establishment_v1(
  p_task_id uuid,p_bed_observations jsonb,p_observed_date date,p_note text,p_idempotency_key text
) returns jsonb language plpgsql security definer set search_path=pg_catalog,atlas as $$
declare
  v_today date:=(now() at time zone 'America/Chicago')::date; v_task atlas.tasks%rowtype; v_lot atlas.production_lots%rowtype; v_key text:=nullif(btrim(p_idempotency_key),'');
  v_expected integer; v_total numeric:=0; v_field_log uuid; v_transition jsonb; v_gate jsonb; v_row record; v_placement atlas.production_transplant_placements%rowtype; v_object atlas.growing_objects%rowtype;
  v_water_task uuid; v_weed_task uuid; v_owner_task uuid;
begin
  if p_task_id is null or p_observed_date is null or p_bed_observations is null or jsonb_typeof(p_bed_observations)<>'array' or jsonb_array_length(p_bed_observations)=0 then raise exception 'Task, observation date, and per-bed establishment counts are required' using errcode='22023'; end if;
  if v_key is null or length(v_key)>120 then raise exception 'A valid establishment idempotency key is required' using errcode='22023'; end if;
  if p_observed_date>v_today+1 then raise exception 'Establishment date cannot be in the future' using errcode='22023'; end if;
  select * into v_task from atlas.tasks where id=p_task_id for update;
  select pl.* into v_lot from atlas.production_lot_tasks plt join atlas.production_lots pl on pl.id=plt.production_lot_id where plt.task_id=p_task_id and plt.link_role='establishment_check' limit 1 for update of pl;
  if v_task.id is null or v_lot.id is null then raise exception 'Task is not a linked production establishment check' using errcode='22023'; end if;
  if exists(select 1 from atlas.field_logs where farm_id=v_lot.farm_id and idempotency_key=left(v_key||':field-log',160)) then return jsonb_build_object('taskId',p_task_id,'productionLotId',v_lot.id,'deduplicated',true); end if;
  if v_task.status not in ('open','blocked') then raise exception 'Establishment task is not open' using errcode='22023'; end if;
  create temporary table if not exists pg_temp.production_establishment_input(placement_id uuid primary key,surviving_plants numeric not null,water_status text not null,weed_pressure text not null) on commit drop;
  truncate pg_temp.production_establishment_input;
  insert into pg_temp.production_establishment_input(placement_id,surviving_plants,water_status,weed_pressure)
  select (x->>'placementId')::uuid,(x->>'survivingPlants')::numeric,x->>'waterStatus',x->>'weedPressure' from jsonb_array_elements(p_bed_observations) x;
  if exists(select 1 from pg_temp.production_establishment_input where surviving_plants<0 or water_status not in ('adequate','needs_water','unknown') or weed_pressure not in ('clear','light','moderate','heavy','unknown')) then raise exception 'Each bed needs a valid survivor count, water status, and weed pressure' using errcode='22023'; end if;
  select count(*) into v_expected from atlas.production_transplant_placements where production_lot_id=v_lot.id;
  if (select count(*) from pg_temp.production_establishment_input)<>v_expected then raise exception 'Every transplanted bed must be counted in the establishment check' using errcode='22023'; end if;
  if exists(select 1 from pg_temp.production_establishment_input i left join atlas.production_transplant_placements p on p.id=i.placement_id and p.production_lot_id=v_lot.id where p.id is null or i.surviving_plants>p.plants_transplanted) then raise exception 'Establishment counts must match this production lot and cannot exceed transplanted plants' using errcode='22023'; end if;
  select sum(surviving_plants) into v_total from pg_temp.production_establishment_input;
  insert into atlas.field_logs(farm_id,log_date,action_types,summary_sentence,note,created_by,source,idempotency_key,metadata)
  values(v_lot.farm_id,p_observed_date,array['establishment','count','production_lot'],'Counted '||v_total::text||' established plants in '||v_lot.lot_label,p_note,'production_stage_engine','production_stage_engine',left(v_key||':field-log',160),jsonb_build_object('production_lot_id',v_lot.id,'observations',p_bed_observations)) returning id into v_field_log;
  for v_row in select * from pg_temp.production_establishment_input loop
    select * into v_placement from atlas.production_transplant_placements where id=v_row.placement_id; select * into v_object from atlas.growing_objects where id=v_placement.object_id;
    insert into atlas.production_field_observations(farm_id,production_lot_id,task_id,object_id,crop_cycle_id,observation_type,outcome,observed_date,quantity,unit,note,idempotency_key,metadata)
    values(v_lot.farm_id,v_lot.id,p_task_id,v_object.id,v_placement.crop_cycle_id,'establishment',case when v_row.surviving_plants>0 then 'established' else 'failed' end,p_observed_date,v_row.surviving_plants,'plants',p_note,left(v_key||':bed:'||v_placement.id::text,160),jsonb_build_object('transplant_placement_id',v_placement.id,'plants_transplanted',v_placement.plants_transplanted,'losses',v_placement.plants_transplanted-v_row.surviving_plants,'water_status',v_row.water_status,'weed_pressure',v_row.weed_pressure));
    insert into atlas.production_field_care_state(farm_id,production_lot_id,object_id,crop_cycle_id,plants_alive,establishment_status,water_status,weed_pressure,pinch_status,last_establishment_check,metadata)
    values(v_lot.farm_id,v_lot.id,v_object.id,v_placement.crop_cycle_id,v_row.surviving_plants,case when v_row.surviving_plants>0 then 'established' else 'failed' end,v_row.water_status,v_row.weed_pressure,'unknown',p_observed_date,jsonb_build_object('transplant_placement_id',v_placement.id,'planting_claim_id',v_placement.planting_claim_id))
    on conflict(production_lot_id,object_id) do update set crop_cycle_id=excluded.crop_cycle_id,plants_alive=excluded.plants_alive,establishment_status=excluded.establishment_status,water_status=excluded.water_status,weed_pressure=excluded.weed_pressure,last_establishment_check=excluded.last_establishment_check,metadata=atlas.production_field_care_state.metadata||excluded.metadata,updated_at=now();
    update atlas.crop_cycles set cycle_state=case when v_row.surviving_plants>0 then 'growing' else 'failed' end,lifecycle_status=case when v_row.surviving_plants>0 then 'active' else 'archived' end,coverage_kind='plants_alive',coverage_amount=v_row.surviving_plants,coverage_unit='plants',metadata=metadata||jsonb_build_object('establishment_checked_date',p_observed_date,'establishment_losses',v_placement.plants_transplanted-v_row.surviving_plants),updated_at=now() where id=v_placement.crop_cycle_id;
    insert into atlas.object_activity_events(farm_id,object_id,field_log_id,crop_cycle_id,event_type,event_date,note,quantity,unit,created_by,source,idempotency_key,metadata)
    values(v_lot.farm_id,v_object.id,v_field_log,v_placement.crop_cycle_id,'checked',p_observed_date,p_note,v_row.surviving_plants,'plants','production_stage_engine','production_stage_engine',left(v_key||':object:'||v_object.id::text,160),jsonb_build_object('observation_type','establishment','production_lot_id',v_lot.id,'transplant_placement_id',v_placement.id,'water_status',v_row.water_status,'weed_pressure',v_row.weed_pressure)) on conflict do nothing;
    insert into atlas.field_log_objects(field_log_id,zone_id,object_id,role) values(v_field_log,v_object.zone_id,v_object.id,'establishment_check') on conflict do nothing;
    insert into atlas.object_state(object_id,farm_id,life_status,weed_pressure,water_status,last_touched_at,last_checked_at,decision_required,harvest_confidence,presentability,metadata)
    values(v_object.id,v_lot.farm_id,case when v_row.surviving_plants>0 then 'growing' else 'failed' end,v_row.weed_pressure,case when v_row.water_status='adequate' then 'irrigated' when v_row.water_status='needs_water' then 'needs_water' else 'unknown' end,p_observed_date,p_observed_date,v_row.surviving_plants=0,'unknown','unknown',jsonb_build_object('production_lot_id',v_lot.id,'plants_alive',v_row.surviving_plants,'last_establishment_task_id',p_task_id))
    on conflict(object_id) do update set life_status=excluded.life_status,weed_pressure=excluded.weed_pressure,water_status=excluded.water_status,last_touched_at=excluded.last_touched_at,last_checked_at=excluded.last_checked_at,decision_required=excluded.decision_required,metadata=atlas.object_state.metadata||excluded.metadata,updated_at=now();
  end loop;
  update atlas.production_lots set current_quantity=v_total,current_unit='plants',current_stage=case when v_total>0 then 'field_care' else 'field_failure_decision' end,metadata=metadata||jsonb_build_object('last_biological_event','establishment_counted','establishment_date',p_observed_date,'establishment_losses',coalesce((metadata->>'transplanted_count')::numeric,0)-v_total),updated_at=now() where id=v_lot.id;
  insert into atlas.production_lot_events(farm_id,production_lot_id,event_type,event_date,quantity,unit,task_id,note,source,idempotency_key,metadata)
  values(v_lot.farm_id,v_lot.id,'establishment_counted',p_observed_date,v_total,'plants',p_task_id,p_note,'production_stage_engine',left(v_key||':event:establishment',160),jsonb_build_object('field_log_id',v_field_log,'observations',p_bed_observations));
  v_transition:=atlas.record_task_transition_v1_internal(p_task_id,'done',left(v_key||':task:done',160),null,coalesce(nullif(btrim(p_note),''),'Counted '||v_total::text||' established plants.'),null,'observe','production_lot',jsonb_build_object('production_lot_id',v_lot.id,'plants_alive',v_total,'bed_observations',p_bed_observations),v_field_log);
  if v_total=0 then
    insert into atlas.tasks(farm_id,title,task_type,status,priority,due_date,generated_from,generated_from_id,note,metadata,action_key,work_class,task_series_key,engine_instance_key,visibility_scope)
    values(v_lot.farm_id,'Owner — Decide field failure recovery — '||v_lot.lot_label,'owner_decision','open','high',p_observed_date,'production_establishment',p_task_id,'No transplanted plants survived establishment. Decide whether to replant, replace, or cancel the crop cohort.',jsonb_build_object('task_key','production_field_failure_'||v_lot.id::text,'owner_task',true,'anna_task',false,'production_lot_id',v_lot.id,'production_lot_key',v_lot.stable_key,'display_action','Decide','display_subject',v_lot.lot_label||' field recovery','display_detail','0 established plants','collection_zone','Owner'),'decide','light','production-lot:'||v_lot.stable_key||':field-failure','production-field-failure:'||v_lot.id::text,'owner') returning id into v_owner_task;
    insert into atlas.production_lot_tasks(production_lot_id,task_id,link_role,source,metadata) values(v_lot.id,v_owner_task,'field_failure_decision','production_stage_engine','{}'::jsonb);
  else
    if exists(select 1 from atlas.production_field_care_state where production_lot_id=v_lot.id and water_status='needs_water') then
      insert into atlas.tasks(farm_id,title,task_type,status,priority,due_date,generated_from,generated_from_id,note,metadata,action_key,work_class,task_series_key,engine_instance_key,visibility_scope,assigned_membership_id)
      values(v_lot.farm_id,'Water establishment cohort — '||v_lot.lot_label,'production_field_care','open','high',p_observed_date,'production_establishment',p_task_id,'Water every linked bed marked needs-water, then confirm completion for the cohort.',jsonb_build_object('task_key','production_field_water_'||p_task_id::text,'task_style','production_field_care','production_lot_id',v_lot.id,'production_lot_key',v_lot.stable_key,'care_action','water','display_action','Water','display_subject',v_lot.lot_label,'display_detail','Establishment cohort','collection_zone','Production beds'),'water','standard','production-lot:'||v_lot.stable_key||':water','production-field-water:'||p_task_id::text,v_task.visibility_scope,v_task.assigned_membership_id) returning id into v_water_task;
      insert into atlas.production_lot_tasks(production_lot_id,task_id,link_role,source,metadata) values(v_lot.id,v_water_task,'water_care','production_stage_engine','{}'::jsonb);
      insert into atlas.task_objects(task_id,object_id,role) select v_water_task,object_id,'target' from atlas.production_field_care_state where production_lot_id=v_lot.id and water_status='needs_water' on conflict do nothing;
      insert into atlas.task_crop_cycles(task_id,crop_cycle_id,role,confidence,source,metadata) select v_water_task,crop_cycle_id,'affects','confirmed','production_stage_engine','{}'::jsonb from atlas.production_field_care_state where production_lot_id=v_lot.id and water_status='needs_water' on conflict do nothing;
    end if;
    if exists(select 1 from atlas.production_field_care_state where production_lot_id=v_lot.id and weed_pressure in ('moderate','heavy')) then
      insert into atlas.tasks(farm_id,title,task_type,status,priority,due_date,generated_from,generated_from_id,note,metadata,action_key,work_class,task_series_key,engine_instance_key,visibility_scope,assigned_membership_id)
      values(v_lot.farm_id,'Weed establishment cohort — '||v_lot.lot_label,'production_field_care','open','high',p_observed_date,'production_establishment',p_task_id,'Weed every linked bed carrying moderate or heavy pressure, then confirm completion for the cohort.',jsonb_build_object('task_key','production_field_weed_'||p_task_id::text,'task_style','production_field_care','production_lot_id',v_lot.id,'production_lot_key',v_lot.stable_key,'care_action','weed','display_action','Weed','display_subject',v_lot.lot_label,'display_detail','Establishment cohort','collection_zone','Production beds'),'weed','standard','production-lot:'||v_lot.stable_key||':weed','production-field-weed:'||p_task_id::text,v_task.visibility_scope,v_task.assigned_membership_id) returning id into v_weed_task;
      insert into atlas.production_lot_tasks(production_lot_id,task_id,link_role,source,metadata) values(v_lot.id,v_weed_task,'weed_care','production_stage_engine','{}'::jsonb);
      insert into atlas.task_objects(task_id,object_id,role) select v_weed_task,object_id,'target' from atlas.production_field_care_state where production_lot_id=v_lot.id and weed_pressure in ('moderate','heavy') on conflict do nothing;
      insert into atlas.task_crop_cycles(task_id,crop_cycle_id,role,confidence,source,metadata) select v_weed_task,crop_cycle_id,'affects','confirmed','production_stage_engine','{}'::jsonb from atlas.production_field_care_state where production_lot_id=v_lot.id and weed_pressure in ('moderate','heavy') on conflict do nothing;
    end if;
  end if;
  v_gate:=atlas.refresh_production_harvest_gate_v1(v_lot.id);
  return jsonb_build_object('taskId',p_task_id,'productionLotId',v_lot.id,'plantsAlive',v_total,'fieldLogId',v_field_log,'waterTaskId',v_water_task,'weedTaskId',v_weed_task,'ownerDecisionTaskId',v_owner_task,'harvestGate',v_gate,'deduplicated',false);
end; $$;